/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityStatus } from './ActivityStatus';
import {
    ActivityStatusFromJSON,
    ActivityStatusFromJSONTyped,
    ActivityStatusToJSON,
    ActivityStatusToJSONTyped,
} from './ActivityStatus';
import type { Chain } from './Chain';
import {
    ChainFromJSON,
    ChainFromJSONTyped,
    ChainToJSON,
    ChainToJSONTyped,
} from './Chain';
import type { ActivityType } from './ActivityType';
import {
    ActivityTypeFromJSON,
    ActivityTypeFromJSONTyped,
    ActivityTypeToJSON,
    ActivityTypeToJSONTyped,
} from './ActivityType';
import type { ActivityDirection } from './ActivityDirection';
import {
    ActivityDirectionFromJSON,
    ActivityDirectionFromJSONTyped,
    ActivityDirectionToJSON,
    ActivityDirectionToJSONTyped,
} from './ActivityDirection';
import type { AssetInfo } from './AssetInfo';
import {
    AssetInfoFromJSON,
    AssetInfoFromJSONTyped,
    AssetInfoToJSON,
    AssetInfoToJSONTyped,
} from './AssetInfo';

/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {ActivityType}
     * @memberof Activity
     */
    activityType: ActivityType;
    /**
     * 
     * @type {ActivityStatus}
     * @memberof Activity
     */
    status: ActivityStatus;
    /**
     * 
     * @type {Date}
     * @memberof Activity
     */
    blockTime: Date;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    blockNumber?: number;
    /**
     * 
     * @type {Chain}
     * @memberof Activity
     */
    fromChain: Chain;
    /**
     * 
     * @type {Chain}
     * @memberof Activity
     */
    toChain: Chain;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    walletAddress?: string;
    /**
     * 
     * @type {ActivityDirection}
     * @memberof Activity
     */
    direction: ActivityDirection;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    fromAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    toAddress?: string;
    /**
     * 
     * @type {AssetInfo}
     * @memberof Activity
     */
    outToken?: AssetInfo;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    outAmount?: string;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    outAmountUsd?: number;
    /**
     * 
     * @type {AssetInfo}
     * @memberof Activity
     */
    inToken?: AssetInfo;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    inAmount?: string;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    inAmountUsd?: number;
    /**
     * 
     * @type {AssetInfo}
     * @memberof Activity
     */
    feeToken?: AssetInfo;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    feeAmount?: string;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    feeAmountUsd?: number;
    /**
     * DEX/bridge protocol name (uniswap_v3, stargate, etc.)
     * @type {string}
     * @memberof Activity
     */
    protocol?: string;
    /**
     * On-chain tx identifiers, format: chain:txhash
     * @type {Array<string>}
     * @memberof Activity
     */
    txIds: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Activity
     */
    isRead?: boolean;
    /**
     * Chain-specific extras (memo, input data, etc.)
     * @type {{ [key: string]: any; }}
     * @memberof Activity
     */
    meta?: { [key: string]: any; };
}



/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
    if ((!('activityType' in (value as Record<string, any>)) && !('activity_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['activityType'] === undefined && (value as Record<string, any>)['activity_type'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('blockTime' in (value as Record<string, any>)) && !('block_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['blockTime'] === undefined && (value as Record<string, any>)['block_time'] === undefined)) return false;
    if ((!('fromChain' in (value as Record<string, any>)) && !('from_chain' in (value as Record<string, any>))) || ((value as Record<string, any>)['fromChain'] === undefined && (value as Record<string, any>)['from_chain'] === undefined)) return false;
    if ((!('toChain' in (value as Record<string, any>)) && !('to_chain' in (value as Record<string, any>))) || ((value as Record<string, any>)['toChain'] === undefined && (value as Record<string, any>)['to_chain'] === undefined)) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if ((!('txIds' in (value as Record<string, any>)) && !('tx_ids' in (value as Record<string, any>))) || ((value as Record<string, any>)['txIds'] === undefined && (value as Record<string, any>)['tx_ids'] === undefined)) return false;
    return true;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if (json == null) {
        return json;
    }
    return {
        
        'activityType': ActivityTypeFromJSON(json['activity_type']),
        'status': ActivityStatusFromJSON(json['status']),
        'blockTime': (new Date(json['block_time'])),
        'blockNumber': json['block_number'] == null ? undefined : json['block_number'],
        'fromChain': ChainFromJSON(json['from_chain']),
        'toChain': ChainFromJSON(json['to_chain']),
        'walletAddress': json['wallet_address'] == null ? undefined : json['wallet_address'],
        'direction': ActivityDirectionFromJSON(json['direction']),
        'fromAddress': json['from_address'] == null ? undefined : json['from_address'],
        'toAddress': json['to_address'] == null ? undefined : json['to_address'],
        'outToken': json['out_token'] == null ? undefined : AssetInfoFromJSON(json['out_token']),
        'outAmount': json['out_amount'] == null ? undefined : json['out_amount'],
        'outAmountUsd': json['out_amount_usd'] == null ? undefined : json['out_amount_usd'],
        'inToken': json['in_token'] == null ? undefined : AssetInfoFromJSON(json['in_token']),
        'inAmount': json['in_amount'] == null ? undefined : json['in_amount'],
        'inAmountUsd': json['in_amount_usd'] == null ? undefined : json['in_amount_usd'],
        'feeToken': json['fee_token'] == null ? undefined : AssetInfoFromJSON(json['fee_token']),
        'feeAmount': json['fee_amount'] == null ? undefined : json['fee_amount'],
        'feeAmountUsd': json['fee_amount_usd'] == null ? undefined : json['fee_amount_usd'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
        'txIds': json['tx_ids'],
        'isRead': json['is_read'] == null ? undefined : json['is_read'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function ActivityToJSON(json: any): Activity {
    return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(value?: Activity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activity_type': ActivityTypeToJSON(value['activityType']),
        'status': ActivityStatusToJSON(value['status']),
        'block_time': value['blockTime'].toISOString(),
        'block_number': value['blockNumber'],
        'from_chain': ChainToJSON(value['fromChain']),
        'to_chain': ChainToJSON(value['toChain']),
        'wallet_address': value['walletAddress'],
        'direction': ActivityDirectionToJSON(value['direction']),
        'from_address': value['fromAddress'],
        'to_address': value['toAddress'],
        'out_token': AssetInfoToJSON(value['outToken']),
        'out_amount': value['outAmount'],
        'out_amount_usd': value['outAmountUsd'],
        'in_token': AssetInfoToJSON(value['inToken']),
        'in_amount': value['inAmount'],
        'in_amount_usd': value['inAmountUsd'],
        'fee_token': AssetInfoToJSON(value['feeToken']),
        'fee_amount': value['feeAmount'],
        'fee_amount_usd': value['feeAmountUsd'],
        'protocol': value['protocol'],
        'tx_ids': value['txIds'],
        'is_read': value['isRead'],
        'meta': value['meta'],
    };
}

