/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ActivityStatus = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Failed: 'failed',
    Dropped: 'dropped'
} as const;
export type ActivityStatus = typeof ActivityStatus[keyof typeof ActivityStatus];


export function instanceOfActivityStatus(value: any): boolean {
    for (const key in ActivityStatus) {
        if (Object.prototype.hasOwnProperty.call(ActivityStatus, key)) {
            if (ActivityStatus[key as keyof typeof ActivityStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActivityStatusFromJSON(json: any): ActivityStatus {
    return ActivityStatusFromJSONTyped(json, false);
}

export function ActivityStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityStatus {
    return json as ActivityStatus;
}

export function ActivityStatusToJSON(value?: ActivityStatus | null): any {
    return value as any;
}

export function ActivityStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ActivityStatus {
    return value as ActivityStatus;
}

