/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ActivityDirection = {
    In: 'in',
    Out: 'out',
    Self: 'self'
} as const;
export type ActivityDirection = typeof ActivityDirection[keyof typeof ActivityDirection];


export function instanceOfActivityDirection(value: any): boolean {
    for (const key in ActivityDirection) {
        if (Object.prototype.hasOwnProperty.call(ActivityDirection, key)) {
            if (ActivityDirection[key as keyof typeof ActivityDirection] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActivityDirectionFromJSON(json: any): ActivityDirection {
    return ActivityDirectionFromJSONTyped(json, false);
}

export function ActivityDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityDirection {
    return json as ActivityDirection;
}

export function ActivityDirectionToJSON(value?: ActivityDirection | null): any {
    return value as any;
}

export function ActivityDirectionToJSONTyped(value: any, ignoreDiscriminator: boolean): ActivityDirection {
    return value as ActivityDirection;
}

