/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetPrice } from './AssetPrice';
import {
    AssetPriceFromJSON,
    AssetPriceFromJSONTyped,
    AssetPriceToJSON,
    AssetPriceToJSONTyped,
} from './AssetPrice';
import type { AssetInfo } from './AssetInfo';
import {
    AssetInfoFromJSON,
    AssetInfoFromJSONTyped,
    AssetInfoToJSON,
    AssetInfoToJSONTyped,
} from './AssetInfo';

/**
 * Balance envelope — token metadata + price + amount
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * 
     * @type {AssetInfo}
     * @memberof Asset
     */
    asset: AssetInfo;
    /**
     * 
     * @type {AssetPrice}
     * @memberof Asset
     */
    price: AssetPrice;
    /**
     * Is asset showed or hidden
     * @type {boolean}
     * @memberof Asset
     */
    isHidden: boolean;
    /**
     * Balance in minimal units (wei, nanoton, satoshi, sun)
     * @type {string}
     * @memberof Asset
     */
    balance: string;
}

/**
 * Check if a given object implements the Asset interface.
 */
export function instanceOfAsset(value: object): value is Asset {
    if (!('asset' in value) || value['asset'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if ((!('isHidden' in (value as Record<string, any>)) && !('is_hidden' in (value as Record<string, any>))) || ((value as Record<string, any>)['isHidden'] === undefined && (value as Record<string, any>)['is_hidden'] === undefined)) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    return true;
}

export function AssetFromJSON(json: any): Asset {
    return AssetFromJSONTyped(json, false);
}

export function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset {
    if (json == null) {
        return json;
    }
    return {
        
        'asset': AssetInfoFromJSON(json['asset']),
        'price': AssetPriceFromJSON(json['price']),
        'isHidden': json['is_hidden'],
        'balance': json['balance'],
    };
}

export function AssetToJSON(json: any): Asset {
    return AssetToJSONTyped(json, false);
}

export function AssetToJSONTyped(value?: Asset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset': AssetInfoToJSON(value['asset']),
        'price': AssetPriceToJSON(value['price']),
        'is_hidden': value['isHidden'],
        'balance': value['balance'],
    };
}

