/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Price info with diffs, keyed by currency (e.g. USD, TON, RUB)
 * @export
 * @interface AssetPrice
 */
export interface AssetPrice {
    /**
     * Current price per currency, e.g. {"USD": "0.999", "TON": "0.789"}
     * @type {{ [key: string]: number; }}
     * @memberof AssetPrice
     */
    prices?: { [key: string]: number; };
    /**
     * Price change over 24h per currency, e.g. {"USD": "-0.06%"}
     * @type {{ [key: string]: string; }}
     * @memberof AssetPrice
     */
    diff24h?: { [key: string]: string; };
    /**
     * Price change over 7d per currency, e.g. {"USD": "-0.05%"}
     * @type {{ [key: string]: string; }}
     * @memberof AssetPrice
     */
    diff7d?: { [key: string]: string; };
    /**
     * Price change over 30d per currency, e.g. {"USD": "-0.06%"}
     * @type {{ [key: string]: string; }}
     * @memberof AssetPrice
     */
    diff30d?: { [key: string]: string; };
}

/**
 * Check if a given object implements the AssetPrice interface.
 */
export function instanceOfAssetPrice(value: object): value is AssetPrice {
    return true;
}

export function AssetPriceFromJSON(json: any): AssetPrice {
    return AssetPriceFromJSONTyped(json, false);
}

export function AssetPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'prices': json['prices'] == null ? undefined : json['prices'],
        'diff24h': json['diff_24h'] == null ? undefined : json['diff_24h'],
        'diff7d': json['diff_7d'] == null ? undefined : json['diff_7d'],
        'diff30d': json['diff_30d'] == null ? undefined : json['diff_30d'],
    };
}

export function AssetPriceToJSON(json: any): AssetPrice {
    return AssetPriceToJSONTyped(json, false);
}

export function AssetPriceToJSONTyped(value?: AssetPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prices': value['prices'],
        'diff_24h': value['diff24h'],
        'diff_7d': value['diff7d'],
        'diff_30d': value['diff30d'],
    };
}

