/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chain } from './Chain';
import {
    ChainFromJSON,
    ChainFromJSONTyped,
    ChainToJSON,
    ChainToJSONTyped,
} from './Chain';

/**
 * 
 * @export
 * @interface BroadcastTxRequest
 */
export interface BroadcastTxRequest {
    /**
     * 
     * @type {Chain}
     * @memberof BroadcastTxRequest
     */
    chain: Chain;
    /**
     * Signed transaction bytes, base64-encoded
     * @type {string}
     * @memberof BroadcastTxRequest
     */
    tx: string;
}



/**
 * Check if a given object implements the BroadcastTxRequest interface.
 */
export function instanceOfBroadcastTxRequest(value: object): value is BroadcastTxRequest {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('tx' in value) || value['tx'] === undefined) return false;
    return true;
}

export function BroadcastTxRequestFromJSON(json: any): BroadcastTxRequest {
    return BroadcastTxRequestFromJSONTyped(json, false);
}

export function BroadcastTxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BroadcastTxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': ChainFromJSON(json['chain']),
        'tx': json['tx'],
    };
}

export function BroadcastTxRequestToJSON(json: any): BroadcastTxRequest {
    return BroadcastTxRequestToJSONTyped(json, false);
}

export function BroadcastTxRequestToJSONTyped(value?: BroadcastTxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': ChainToJSON(value['chain']),
        'tx': value['tx'],
    };
}

