/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BroadcastTx200Response
 */
export interface BroadcastTx200Response {
    /**
     * 
     * @type {string}
     * @memberof BroadcastTx200Response
     */
    txHash: string;
}

/**
 * Check if a given object implements the BroadcastTx200Response interface.
 */
export function instanceOfBroadcastTx200Response(value: object): value is BroadcastTx200Response {
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    return true;
}

export function BroadcastTx200ResponseFromJSON(json: any): BroadcastTx200Response {
    return BroadcastTx200ResponseFromJSONTyped(json, false);
}

export function BroadcastTx200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BroadcastTx200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'txHash': json['txHash'],
    };
}

export function BroadcastTx200ResponseToJSON(json: any): BroadcastTx200Response {
    return BroadcastTx200ResponseToJSONTyped(json, false);
}

export function BroadcastTx200ResponseToJSONTyped(value?: BroadcastTx200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'txHash': value['txHash'],
    };
}

