/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainSyncStatus
 */
export interface ChainSyncStatus {
    /**
     * - `ok`          — fresh snapshot from this priming/sync cycle.
     * - `stale`       — current fetch failed, but a previous snapshot is
     *   still served from DB; client may show a "last updated …"
     *   affordance.
     * - `unavailable` — fetch failed and no cached snapshot to fall back
     *   to.
     * 
     * @type {ChainSyncStatusStatusEnum}
     * @memberof ChainSyncStatus
     */
    status: ChainSyncStatusStatusEnum;
    /**
     * When balances for this chain were last successfully snapshotted.
     * @type {Date}
     * @memberof ChainSyncStatus
     */
    balancesAt?: Date;
    /**
     * When the first activity page for this chain was last successfully fetched.
     * @type {Date}
     * @memberof ChainSyncStatus
     */
    activityAt?: Date;
    /**
     * Set when status is stale or unavailable, identifying the failure mode.
     * @type {ChainSyncStatusReasonEnum}
     * @memberof ChainSyncStatus
     */
    reason?: ChainSyncStatusReasonEnum;
    /**
     * Server-suggested backoff for the client when this chain is rate-limited.
     * @type {number}
     * @memberof ChainSyncStatus
     */
    retryAfterMs?: number;
    /**
     * Deep-history catch-up state; clients poll until `complete`.
     * @type {ChainSyncStatusBackfillEnum}
     * @memberof ChainSyncStatus
     */
    backfill: ChainSyncStatusBackfillEnum;
}


/**
 * @export
 */
export const ChainSyncStatusStatusEnum = {
    Ok: 'ok',
    Stale: 'stale',
    Unavailable: 'unavailable'
} as const;
export type ChainSyncStatusStatusEnum = typeof ChainSyncStatusStatusEnum[keyof typeof ChainSyncStatusStatusEnum];

/**
 * @export
 */
export const ChainSyncStatusReasonEnum = {
    ProviderTimeout: 'provider_timeout',
    Provider5xx: 'provider_5xx',
    RateLimited: 'rate_limited',
    CircuitOpen: 'circuit_open',
    CapabilityNotSupported: 'capability_not_supported'
} as const;
export type ChainSyncStatusReasonEnum = typeof ChainSyncStatusReasonEnum[keyof typeof ChainSyncStatusReasonEnum];

/**
 * @export
 */
export const ChainSyncStatusBackfillEnum = {
    Complete: 'complete',
    InProgress: 'in_progress',
    Queued: 'queued'
} as const;
export type ChainSyncStatusBackfillEnum = typeof ChainSyncStatusBackfillEnum[keyof typeof ChainSyncStatusBackfillEnum];


/**
 * Check if a given object implements the ChainSyncStatus interface.
 */
export function instanceOfChainSyncStatus(value: object): value is ChainSyncStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('backfill' in value) || value['backfill'] === undefined) return false;
    return true;
}

export function ChainSyncStatusFromJSON(json: any): ChainSyncStatus {
    return ChainSyncStatusFromJSONTyped(json, false);
}

export function ChainSyncStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainSyncStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'balancesAt': json['balances_at'] == null ? undefined : (new Date(json['balances_at'])),
        'activityAt': json['activity_at'] == null ? undefined : (new Date(json['activity_at'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'retryAfterMs': json['retry_after_ms'] == null ? undefined : json['retry_after_ms'],
        'backfill': json['backfill'],
    };
}

export function ChainSyncStatusToJSON(json: any): ChainSyncStatus {
    return ChainSyncStatusToJSONTyped(json, false);
}

export function ChainSyncStatusToJSONTyped(value?: ChainSyncStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'balances_at': value['balancesAt'] == null ? value['balancesAt'] : value['balancesAt'].toISOString(),
        'activity_at': value['activityAt'] == null ? value['activityAt'] : value['activityAt'].toISOString(),
        'reason': value['reason'],
        'retry_after_ms': value['retryAfterMs'],
        'backfill': value['backfill'],
    };
}

