/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chain } from './Chain';
import {
    ChainFromJSON,
    ChainFromJSONTyped,
    ChainToJSON,
    ChainToJSONTyped,
} from './Chain';
import type { ChainExplorer } from './ChainExplorer';
import {
    ChainExplorerFromJSON,
    ChainExplorerFromJSONTyped,
    ChainExplorerToJSON,
    ChainExplorerToJSONTyped,
} from './ChainExplorer';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
    NetworkToJSONTyped,
} from './Network';

/**
 * 
 * @export
 * @interface ChainNode
 */
export interface ChainNode {
    /**
     * 
     * @type {Chain}
     * @memberof ChainNode
     */
    chain: Chain;
    /**
     * 
     * @type {Network}
     * @memberof ChainNode
     */
    network: Network;
    /**
     * Human-readable chain name
     * @type {string}
     * @memberof ChainNode
     */
    name: string;
    /**
     * 
     * @type {ChainExplorer}
     * @memberof ChainNode
     */
    explorer: ChainExplorer;
}



/**
 * Check if a given object implements the ChainNode interface.
 */
export function instanceOfChainNode(value: object): value is ChainNode {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('explorer' in value) || value['explorer'] === undefined) return false;
    return true;
}

export function ChainNodeFromJSON(json: any): ChainNode {
    return ChainNodeFromJSONTyped(json, false);
}

export function ChainNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainNode {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': ChainFromJSON(json['chain']),
        'network': NetworkFromJSON(json['network']),
        'name': json['name'],
        'explorer': ChainExplorerFromJSON(json['explorer']),
    };
}

export function ChainNodeToJSON(json: any): ChainNode {
    return ChainNodeToJSONTyped(json, false);
}

export function ChainNodeToJSONTyped(value?: ChainNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': ChainToJSON(value['chain']),
        'network': NetworkToJSON(value['network']),
        'name': value['name'],
        'explorer': ChainExplorerToJSON(value['explorer']),
    };
}

