/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Block-explorer URL templates for this chain+network. Substitute placeholders (e.g. {tx_hash}) to build a clickable link. EVM chains follow EIP-3091; non-EVM chains expose the same template shape.
 * @export
 * @interface ChainExplorer
 */
export interface ChainExplorer {
    /**
     * Transaction URL template. Replace {tx_hash} with the on-chain transaction hash.
     * @type {string}
     * @memberof ChainExplorer
     */
    txUrl: string;
}

/**
 * Check if a given object implements the ChainExplorer interface.
 */
export function instanceOfChainExplorer(value: object): value is ChainExplorer {
    if ((!('txUrl' in (value as Record<string, any>)) && !('tx_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['txUrl'] === undefined && (value as Record<string, any>)['tx_url'] === undefined)) return false;
    return true;
}

export function ChainExplorerFromJSON(json: any): ChainExplorer {
    return ChainExplorerFromJSONTyped(json, false);
}

export function ChainExplorerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainExplorer {
    if (json == null) {
        return json;
    }
    return {
        
        'txUrl': json['tx_url'],
    };
}

export function ChainExplorerToJSON(json: any): ChainExplorer {
    return ChainExplorerToJSONTyped(json, false);
}

export function ChainExplorerToJSONTyped(value?: ChainExplorer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tx_url': value['txUrl'],
    };
}

