/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeeEstimate
 */
export interface FeeEstimate {
    /**
     * Fee estimate for slow confirmation
     * @type {string}
     * @memberof FeeEstimate
     */
    slow: string;
    /**
     * Fee estimate for normal confirmation
     * @type {string}
     * @memberof FeeEstimate
     */
    normal: string;
    /**
     * Fee estimate for fast confirmation
     * @type {string}
     * @memberof FeeEstimate
     */
    fast: string;
}

/**
 * Check if a given object implements the FeeEstimate interface.
 */
export function instanceOfFeeEstimate(value: object): value is FeeEstimate {
    if (!('slow' in value) || value['slow'] === undefined) return false;
    if (!('normal' in value) || value['normal'] === undefined) return false;
    if (!('fast' in value) || value['fast'] === undefined) return false;
    return true;
}

export function FeeEstimateFromJSON(json: any): FeeEstimate {
    return FeeEstimateFromJSONTyped(json, false);
}

export function FeeEstimateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeeEstimate {
    if (json == null) {
        return json;
    }
    return {
        
        'slow': json['slow'],
        'normal': json['normal'],
        'fast': json['fast'],
    };
}

export function FeeEstimateToJSON(json: any): FeeEstimate {
    return FeeEstimateToJSONTyped(json, false);
}

export function FeeEstimateToJSONTyped(value?: FeeEstimate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slow': value['slow'],
        'normal': value['normal'],
        'fast': value['fast'],
    };
}

