/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChainNode } from './ChainNode';
import {
    ChainNodeFromJSON,
    ChainNodeFromJSONTyped,
    ChainNodeToJSON,
    ChainNodeToJSONTyped,
} from './ChainNode';

/**
 * 
 * @export
 * @interface GetNodes200Response
 */
export interface GetNodes200Response {
    /**
     * 
     * @type {Array<ChainNode>}
     * @memberof GetNodes200Response
     */
    nodes: Array<ChainNode>;
}

/**
 * Check if a given object implements the GetNodes200Response interface.
 */
export function instanceOfGetNodes200Response(value: object): value is GetNodes200Response {
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    return true;
}

export function GetNodes200ResponseFromJSON(json: any): GetNodes200Response {
    return GetNodes200ResponseFromJSONTyped(json, false);
}

export function GetNodes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNodes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': ((json['nodes'] as Array<any>).map(ChainNodeFromJSON)),
    };
}

export function GetNodes200ResponseToJSON(json: any): GetNodes200Response {
    return GetNodes200ResponseToJSONTyped(json, false);
}

export function GetNodes200ResponseToJSONTyped(value?: GetNodes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodes': ((value['nodes'] as Array<any>).map(ChainNodeToJSON)),
    };
}

