/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';

/**
 * 
 * @export
 * @interface GetWalletAssets200Response
 */
export interface GetWalletAssets200Response {
    /**
     * 
     * @type {Array<Asset>}
     * @memberof GetWalletAssets200Response
     */
    assets: Array<Asset>;
    /**
     * Current price per currency, e.g. {"USD": "0.999", "TON": "0.789"}
     * @type {{ [key: string]: string; }}
     * @memberof GetWalletAssets200Response
     */
    fiatPrice: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof GetWalletAssets200Response
     */
    nextCursor: string;
}

/**
 * Check if a given object implements the GetWalletAssets200Response interface.
 */
export function instanceOfGetWalletAssets200Response(value: object): value is GetWalletAssets200Response {
    if (!('assets' in value) || value['assets'] === undefined) return false;
    if ((!('fiatPrice' in (value as Record<string, any>)) && !('fiat_price' in (value as Record<string, any>))) || ((value as Record<string, any>)['fiatPrice'] === undefined && (value as Record<string, any>)['fiat_price'] === undefined)) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function GetWalletAssets200ResponseFromJSON(json: any): GetWalletAssets200Response {
    return GetWalletAssets200ResponseFromJSONTyped(json, false);
}

export function GetWalletAssets200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWalletAssets200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'assets': ((json['assets'] as Array<any>).map(AssetFromJSON)),
        'fiatPrice': json['fiat_price'],
        'nextCursor': json['next_cursor'],
    };
}

export function GetWalletAssets200ResponseToJSON(json: any): GetWalletAssets200Response {
    return GetWalletAssets200ResponseToJSONTyped(json, false);
}

export function GetWalletAssets200ResponseToJSONTyped(value?: GetWalletAssets200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assets': ((value['assets'] as Array<any>).map(AssetToJSON)),
        'fiat_price': value['fiatPrice'],
        'next_cursor': value['nextCursor'],
    };
}

