/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Activity } from './Activity';
import {
    ActivityFromJSON,
    ActivityFromJSONTyped,
    ActivityToJSON,
    ActivityToJSONTyped,
} from './Activity';

/**
 * 
 * @export
 * @interface GetWalletActivities200Response
 */
export interface GetWalletActivities200Response {
    /**
     * 
     * @type {Array<Activity>}
     * @memberof GetWalletActivities200Response
     */
    activities: Array<Activity>;
    /**
     * Cursor for next page, empty if no more data
     * @type {string}
     * @memberof GetWalletActivities200Response
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the GetWalletActivities200Response interface.
 */
export function instanceOfGetWalletActivities200Response(value: object): value is GetWalletActivities200Response {
    if (!('activities' in value) || value['activities'] === undefined) return false;
    return true;
}

export function GetWalletActivities200ResponseFromJSON(json: any): GetWalletActivities200Response {
    return GetWalletActivities200ResponseFromJSONTyped(json, false);
}

export function GetWalletActivities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWalletActivities200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'activities': ((json['activities'] as Array<any>).map(ActivityFromJSON)),
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function GetWalletActivities200ResponseToJSON(json: any): GetWalletActivities200Response {
    return GetWalletActivities200ResponseToJSONTyped(json, false);
}

export function GetWalletActivities200ResponseToJSONTyped(value?: GetWalletActivities200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activities': ((value['activities'] as Array<any>).map(ActivityToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

