/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Healthcheck500Response
 */
export interface Healthcheck500Response {
    /**
     * 
     * @type {string}
     * @memberof Healthcheck500Response
     */
    error: string;
}

/**
 * Check if a given object implements the Healthcheck500Response interface.
 */
export function instanceOfHealthcheck500Response(value: object): value is Healthcheck500Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function Healthcheck500ResponseFromJSON(json: any): Healthcheck500Response {
    return Healthcheck500ResponseFromJSONTyped(json, false);
}

export function Healthcheck500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Healthcheck500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function Healthcheck500ResponseToJSON(json: any): Healthcheck500Response {
    return Healthcheck500ResponseToJSONTyped(json, false);
}

export function Healthcheck500ResponseToJSONTyped(value?: Healthcheck500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

