/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Network = {
    Mainnet: 'mainnet',
    Testnet: 'testnet'
} as const;
export type Network = typeof Network[keyof typeof Network];


export function instanceOfNetwork(value: any): boolean {
    for (const key in Network) {
        if (Object.prototype.hasOwnProperty.call(Network, key)) {
            if (Network[key as keyof typeof Network] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NetworkFromJSON(json: any): Network {
    return NetworkFromJSONTyped(json, false);
}

export function NetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Network {
    return json as Network;
}

export function NetworkToJSON(value?: Network | null): any {
    return value as any;
}

export function NetworkToJSONTyped(value: any, ignoreDiscriminator: boolean): Network {
    return value as Network;
}

