/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletAccount } from './WalletAccount';
import {
    WalletAccountFromJSON,
    WalletAccountFromJSONTyped,
    WalletAccountToJSON,
    WalletAccountToJSONTyped,
} from './WalletAccount';

/**
 * 
 * @export
 * @interface RegisterWalletRequest
 */
export interface RegisterWalletRequest {
    /**
     * Stable wallet identifier
     * @type {string}
     * @memberof RegisterWalletRequest
     */
    walletId: string;
    /**
     * 
     * @type {Array<WalletAccount>}
     * @memberof RegisterWalletRequest
     */
    accounts: Array<WalletAccount>;
}

/**
 * Check if a given object implements the RegisterWalletRequest interface.
 */
export function instanceOfRegisterWalletRequest(value: object): value is RegisterWalletRequest {
    if ((!('walletId' in (value as Record<string, any>)) && !('wallet_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['walletId'] === undefined && (value as Record<string, any>)['wallet_id'] === undefined)) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function RegisterWalletRequestFromJSON(json: any): RegisterWalletRequest {
    return RegisterWalletRequestFromJSONTyped(json, false);
}

export function RegisterWalletRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterWalletRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'walletId': json['wallet_id'],
        'accounts': ((json['accounts'] as Array<any>).map(WalletAccountFromJSON)),
    };
}

export function RegisterWalletRequestToJSON(json: any): RegisterWalletRequest {
    return RegisterWalletRequestToJSONTyped(json, false);
}

export function RegisterWalletRequestToJSONTyped(value?: RegisterWalletRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wallet_id': value['walletId'],
        'accounts': ((value['accounts'] as Array<any>).map(WalletAccountToJSON)),
    };
}

