/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveWalletAssetsFiltersRequestChangesInner
 */
export interface SaveWalletAssetsFiltersRequestChangesInner {
    /**
     * 
     * @type {string}
     * @memberof SaveWalletAssetsFiltersRequestChangesInner
     */
    assetId: string;
    /**
     * 
     * @type {SaveWalletAssetsFiltersRequestChangesInnerActionEnum}
     * @memberof SaveWalletAssetsFiltersRequestChangesInner
     */
    action: SaveWalletAssetsFiltersRequestChangesInnerActionEnum;
}


/**
 * @export
 */
export const SaveWalletAssetsFiltersRequestChangesInnerActionEnum = {
    Show: 'show',
    Hide: 'hide'
} as const;
export type SaveWalletAssetsFiltersRequestChangesInnerActionEnum = typeof SaveWalletAssetsFiltersRequestChangesInnerActionEnum[keyof typeof SaveWalletAssetsFiltersRequestChangesInnerActionEnum];


/**
 * Check if a given object implements the SaveWalletAssetsFiltersRequestChangesInner interface.
 */
export function instanceOfSaveWalletAssetsFiltersRequestChangesInner(value: object): value is SaveWalletAssetsFiltersRequestChangesInner {
    if ((!('assetId' in (value as Record<string, any>)) && !('asset_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['assetId'] === undefined && (value as Record<string, any>)['asset_id'] === undefined)) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function SaveWalletAssetsFiltersRequestChangesInnerFromJSON(json: any): SaveWalletAssetsFiltersRequestChangesInner {
    return SaveWalletAssetsFiltersRequestChangesInnerFromJSONTyped(json, false);
}

export function SaveWalletAssetsFiltersRequestChangesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveWalletAssetsFiltersRequestChangesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['asset_id'],
        'action': json['action'],
    };
}

export function SaveWalletAssetsFiltersRequestChangesInnerToJSON(json: any): SaveWalletAssetsFiltersRequestChangesInner {
    return SaveWalletAssetsFiltersRequestChangesInnerToJSONTyped(json, false);
}

export function SaveWalletAssetsFiltersRequestChangesInnerToJSONTyped(value?: SaveWalletAssetsFiltersRequestChangesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset_id': value['assetId'],
        'action': value['action'],
    };
}

