/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaveWalletAssetsFiltersRequestChangesInner } from './SaveWalletAssetsFiltersRequestChangesInner';
import {
    SaveWalletAssetsFiltersRequestChangesInnerFromJSON,
    SaveWalletAssetsFiltersRequestChangesInnerFromJSONTyped,
    SaveWalletAssetsFiltersRequestChangesInnerToJSON,
    SaveWalletAssetsFiltersRequestChangesInnerToJSONTyped,
} from './SaveWalletAssetsFiltersRequestChangesInner';

/**
 * 
 * @export
 * @interface SaveWalletAssetsFiltersRequest
 */
export interface SaveWalletAssetsFiltersRequest {
    /**
     * 
     * @type {Array<SaveWalletAssetsFiltersRequestChangesInner>}
     * @memberof SaveWalletAssetsFiltersRequest
     */
    changes: Array<SaveWalletAssetsFiltersRequestChangesInner>;
}

/**
 * Check if a given object implements the SaveWalletAssetsFiltersRequest interface.
 */
export function instanceOfSaveWalletAssetsFiltersRequest(value: object): value is SaveWalletAssetsFiltersRequest {
    if (!('changes' in value) || value['changes'] === undefined) return false;
    return true;
}

export function SaveWalletAssetsFiltersRequestFromJSON(json: any): SaveWalletAssetsFiltersRequest {
    return SaveWalletAssetsFiltersRequestFromJSONTyped(json, false);
}

export function SaveWalletAssetsFiltersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveWalletAssetsFiltersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'changes': ((json['changes'] as Array<any>).map(SaveWalletAssetsFiltersRequestChangesInnerFromJSON)),
    };
}

export function SaveWalletAssetsFiltersRequestToJSON(json: any): SaveWalletAssetsFiltersRequest {
    return SaveWalletAssetsFiltersRequestToJSONTyped(json, false);
}

export function SaveWalletAssetsFiltersRequestToJSONTyped(value?: SaveWalletAssetsFiltersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changes': ((value['changes'] as Array<any>).map(SaveWalletAssetsFiltersRequestChangesInnerToJSON)),
    };
}

