/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SummaryAsset } from './SummaryAsset';
import {
    SummaryAssetFromJSON,
    SummaryAssetFromJSONTyped,
    SummaryAssetToJSON,
    SummaryAssetToJSONTyped,
} from './SummaryAsset';

/**
 * 
 * @export
 * @interface SearchAssets200Response
 */
export interface SearchAssets200Response {
    /**
     * 
     * @type {Array<SummaryAsset>}
     * @memberof SearchAssets200Response
     */
    assets: Array<SummaryAsset>;
    /**
     * 
     * @type {string}
     * @memberof SearchAssets200Response
     */
    nextCursor: string;
}

/**
 * Check if a given object implements the SearchAssets200Response interface.
 */
export function instanceOfSearchAssets200Response(value: object): value is SearchAssets200Response {
    if (!('assets' in value) || value['assets'] === undefined) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function SearchAssets200ResponseFromJSON(json: any): SearchAssets200Response {
    return SearchAssets200ResponseFromJSONTyped(json, false);
}

export function SearchAssets200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAssets200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'assets': ((json['assets'] as Array<any>).map(SummaryAssetFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function SearchAssets200ResponseToJSON(json: any): SearchAssets200Response {
    return SearchAssets200ResponseToJSONTyped(json, false);
}

export function SearchAssets200ResponseToJSONTyped(value?: SearchAssets200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assets': ((value['assets'] as Array<any>).map(SummaryAssetToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

