/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetPrice } from './AssetPrice';
import {
    AssetPriceFromJSON,
    AssetPriceFromJSONTyped,
    AssetPriceToJSON,
    AssetPriceToJSONTyped,
} from './AssetPrice';
import type { AssetInfo } from './AssetInfo';
import {
    AssetInfoFromJSON,
    AssetInfoFromJSONTyped,
    AssetInfoToJSON,
    AssetInfoToJSONTyped,
} from './AssetInfo';

/**
 * Balance envelope — token metadata + price + amount
 * @export
 * @interface SummaryAsset
 */
export interface SummaryAsset {
    /**
     * 
     * @type {AssetInfo}
     * @memberof SummaryAsset
     */
    asset: AssetInfo;
    /**
     * 
     * @type {AssetPrice}
     * @memberof SummaryAsset
     */
    price: AssetPrice;
    /**
     * Current price per currency, e.g. {"USD": "0.999", "TON": "0.789"}
     * @type {{ [key: string]: string; }}
     * @memberof SummaryAsset
     */
    marketCap: { [key: string]: string; };
}

/**
 * Check if a given object implements the SummaryAsset interface.
 */
export function instanceOfSummaryAsset(value: object): value is SummaryAsset {
    if (!('asset' in value) || value['asset'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if ((!('marketCap' in (value as Record<string, any>)) && !('market_cap' in (value as Record<string, any>))) || ((value as Record<string, any>)['marketCap'] === undefined && (value as Record<string, any>)['market_cap'] === undefined)) return false;
    return true;
}

export function SummaryAssetFromJSON(json: any): SummaryAsset {
    return SummaryAssetFromJSONTyped(json, false);
}

export function SummaryAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'asset': AssetInfoFromJSON(json['asset']),
        'price': AssetPriceFromJSON(json['price']),
        'marketCap': json['market_cap'],
    };
}

export function SummaryAssetToJSON(json: any): SummaryAsset {
    return SummaryAssetToJSONTyped(json, false);
}

export function SummaryAssetToJSONTyped(value?: SummaryAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset': AssetInfoToJSON(value['asset']),
        'price': AssetPriceToJSON(value['price']),
        'market_cap': value['marketCap'],
    };
}

