/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletAccount } from './WalletAccount';
import {
    WalletAccountFromJSON,
    WalletAccountFromJSONTyped,
    WalletAccountToJSON,
    WalletAccountToJSONTyped,
} from './WalletAccount';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
    NetworkToJSONTyped,
} from './Network';
import type { WalletKind } from './WalletKind';
import {
    WalletKindFromJSON,
    WalletKindFromJSONTyped,
    WalletKindToJSON,
    WalletKindToJSONTyped,
} from './WalletKind';

/**
 * 
 * @export
 * @interface SyncWalletV2Request
 */
export interface SyncWalletV2Request {
    /**
     * 
     * @type {WalletKind}
     * @memberof SyncWalletV2Request
     */
    kind: WalletKind;
    /**
     * 
     * @type {Network}
     * @memberof SyncWalletV2Request
     */
    network: Network;
    /**
     * Wallet derivation/registration scheme version. Bound into wallet_id derivation.
     * @type {number}
     * @memberof SyncWalletV2Request
     */
    version?: number;
    /**
     * The base64url challenge previously minted via GET /api/v2/wallets/challenge
     * @type {string}
     * @memberof SyncWalletV2Request
     */
    challenge?: string;
    /**
     * Root public key, hex-encoded. 32 bytes (64 hex) for ed25519 (multichain/chain); 33 bytes compressed (66 hex) for secp256k1 (unichain). Required when kind is not watch.
     * @type {string}
     * @memberof SyncWalletV2Request
     */
    rootPub?: string;
    /**
     * Root proof signature over the canonical registration message. Ed25519: 64 bytes (128 hex). Secp256k1: DER-encoded ECDSA over blake2b-256(message), variable length up to ~74 bytes (148 hex). Required when kind is not watch.
     * @type {string}
     * @memberof SyncWalletV2Request
     */
    rootProof?: string;
    /**
     * For kind=watch this MUST contain exactly one entry.
     * @type {Array<WalletAccount>}
     * @memberof SyncWalletV2Request
     */
    accounts: Array<WalletAccount>;
}



/**
 * Check if a given object implements the SyncWalletV2Request interface.
 */
export function instanceOfSyncWalletV2Request(value: object): value is SyncWalletV2Request {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function SyncWalletV2RequestFromJSON(json: any): SyncWalletV2Request {
    return SyncWalletV2RequestFromJSONTyped(json, false);
}

export function SyncWalletV2RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncWalletV2Request {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': WalletKindFromJSON(json['kind']),
        'network': NetworkFromJSON(json['network']),
        'version': json['version'] == null ? undefined : json['version'],
        'challenge': json['challenge'] == null ? undefined : json['challenge'],
        'rootPub': json['root_pub'] == null ? undefined : json['root_pub'],
        'rootProof': json['root_proof'] == null ? undefined : json['root_proof'],
        'accounts': ((json['accounts'] as Array<any>).map(WalletAccountFromJSON)),
    };
}

export function SyncWalletV2RequestToJSON(json: any): SyncWalletV2Request {
    return SyncWalletV2RequestToJSONTyped(json, false);
}

export function SyncWalletV2RequestToJSONTyped(value?: SyncWalletV2Request | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': WalletKindToJSON(value['kind']),
        'network': NetworkToJSON(value['network']),
        'version': value['version'],
        'challenge': value['challenge'],
        'root_pub': value['rootPub'],
        'root_proof': value['rootProof'],
        'accounts': ((value['accounts'] as Array<any>).map(WalletAccountToJSON)),
    };
}

