/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChainSyncStatus } from './ChainSyncStatus';
import {
    ChainSyncStatusFromJSON,
    ChainSyncStatusFromJSONTyped,
    ChainSyncStatusToJSON,
    ChainSyncStatusToJSONTyped,
} from './ChainSyncStatus';

/**
 * Wallet-level data freshness rollup. Returned on `POST /wallets` after
 * the priming window (≤5s) and on `GET /wallets/{wallet_id}/sync_status`
 * as the client polls until backfill completes. HTTP is always 200 when
 * the request itself is valid — branch on `status` instead.
 * 
 * @export
 * @interface SyncStatus
 */
export interface SyncStatus {
    /**
     * Top-level rollup over per-chain statuses:
     * - `ready`    — every chain is `ok`.
     * - `partial`  — at least one chain is `stale` (cached snapshot served
     *   while a re-fetch is pending); rest are `ok`.
     * - `degraded` — at least one chain is `unavailable`, but at least
     *   one chain is still serving `ok`/`stale` data.
     * - `failed`  — every chain is `unavailable`; the wallet has nothing
     *   fresh to render. The client should surface a retryable error
     *   instead of drawing empty balances.
     * 
     * @type {SyncStatusStatusEnum}
     * @memberof SyncStatus
     */
    status: SyncStatusStatusEnum;
    /**
     * Per-chain freshness, keyed by Chain enum value (e.g. "ton", "eth").
     * @type {{ [key: string]: ChainSyncStatus; }}
     * @memberof SyncStatus
     */
    chains: { [key: string]: ChainSyncStatus; };
}


/**
 * @export
 */
export const SyncStatusStatusEnum = {
    Ready: 'ready',
    Partial: 'partial',
    Degraded: 'degraded',
    Failed: 'failed'
} as const;
export type SyncStatusStatusEnum = typeof SyncStatusStatusEnum[keyof typeof SyncStatusStatusEnum];


/**
 * Check if a given object implements the SyncStatus interface.
 */
export function instanceOfSyncStatus(value: object): value is SyncStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('chains' in value) || value['chains'] === undefined) return false;
    return true;
}

export function SyncStatusFromJSON(json: any): SyncStatus {
    return SyncStatusFromJSONTyped(json, false);
}

export function SyncStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'chains': (mapValues(json['chains'], ChainSyncStatusFromJSON)),
    };
}

export function SyncStatusToJSON(json: any): SyncStatus {
    return SyncStatusToJSONTyped(json, false);
}

export function SyncStatusToJSONTyped(value?: SyncStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'chains': (mapValues(value['chains'], ChainSyncStatusToJSON)),
    };
}

