/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * v2 wallet kind:
 * - `multichain` — one ed25519 root key derives addresses across many chains.
 * - `chain`      — one ed25519 root key bound to a single chain.
 * - `unichain`   — one secp256k1 root key (EVM-style); compressed pub + DER ECDSA proof.
 * - `watch`      — read-only registration of a foreign address (no key, no proof).
 * 
 * @export
 */
export const WalletKind = {
    Multichain: 'multichain',
    Chain: 'chain',
    Unichain: 'unichain',
    Watch: 'watch'
} as const;
export type WalletKind = typeof WalletKind[keyof typeof WalletKind];


export function instanceOfWalletKind(value: any): boolean {
    for (const key in WalletKind) {
        if (Object.prototype.hasOwnProperty.call(WalletKind, key)) {
            if (WalletKind[key as keyof typeof WalletKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WalletKindFromJSON(json: any): WalletKind {
    return WalletKindFromJSONTyped(json, false);
}

export function WalletKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletKind {
    return json as WalletKind;
}

export function WalletKindToJSON(value?: WalletKind | null): any {
    return value as any;
}

export function WalletKindToJSONTyped(value: any, ignoreDiscriminator: boolean): WalletKind {
    return value as WalletKind;
}

