/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chain } from './Chain';
import {
    ChainFromJSON,
    ChainFromJSONTyped,
    ChainToJSON,
    ChainToJSONTyped,
} from './Chain';

/**
 * 
 * @export
 * @interface WalletAccount
 */
export interface WalletAccount {
    /**
     * 
     * @type {Chain}
     * @memberof WalletAccount
     */
    chain: Chain;
    /**
     * 
     * @type {string}
     * @memberof WalletAccount
     */
    address: string;
    /**
     * TON wallet contract revisions: v3R1, v3R2, v4R1, v4R2, v5R1.
     * BTC script types: p2pkh, p2sh-p2wpkh, p2wpkh, p2tr.
     * Omit for EVM/TRON.
     * 
     * @type {WalletAccountTypeEnum}
     * @memberof WalletAccount
     */
    type?: WalletAccountTypeEnum;
}


/**
 * @export
 */
export const WalletAccountTypeEnum = {
    V3R1: 'v3R1',
    V3R2: 'v3R2',
    V4R1: 'v4R1',
    V4R2: 'v4R2',
    V5R1: 'v5R1',
    P2pkh: 'p2pkh',
    P2shP2wpkh: 'p2sh-p2wpkh',
    P2wpkh: 'p2wpkh',
    P2tr: 'p2tr'
} as const;
export type WalletAccountTypeEnum = typeof WalletAccountTypeEnum[keyof typeof WalletAccountTypeEnum];


/**
 * Check if a given object implements the WalletAccount interface.
 */
export function instanceOfWalletAccount(value: object): value is WalletAccount {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function WalletAccountFromJSON(json: any): WalletAccount {
    return WalletAccountFromJSONTyped(json, false);
}

export function WalletAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': ChainFromJSON(json['chain']),
        'address': json['address'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function WalletAccountToJSON(json: any): WalletAccount {
    return WalletAccountToJSONTyped(json, false);
}

export function WalletAccountToJSONTyped(value?: WalletAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': ChainToJSON(value['chain']),
        'address': value['address'],
        'type': value['type'],
    };
}

