/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletAccount } from './WalletAccount';
import {
    WalletAccountFromJSON,
    WalletAccountFromJSONTyped,
    WalletAccountToJSON,
    WalletAccountToJSONTyped,
} from './WalletAccount';
import type { SyncStatus } from './SyncStatus';
import {
    SyncStatusFromJSON,
    SyncStatusFromJSONTyped,
    SyncStatusToJSON,
    SyncStatusToJSONTyped,
} from './SyncStatus';

/**
 * 
 * @export
 * @interface Wallet
 */
export interface Wallet {
    /**
     * Stable wallet identifier
     * @type {string}
     * @memberof Wallet
     */
    walletId: string;
    /**
     * 
     * @type {Array<WalletAccount>}
     * @memberof Wallet
     */
    accounts: Array<WalletAccount>;
    /**
     * 
     * @type {Date}
     * @memberof Wallet
     */
    createdAt: Date;
    /**
     * 
     * @type {SyncStatus}
     * @memberof Wallet
     */
    syncStatus: SyncStatus;
}

/**
 * Check if a given object implements the Wallet interface.
 */
export function instanceOfWallet(value: object): value is Wallet {
    if ((!('walletId' in (value as Record<string, any>)) && !('wallet_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['walletId'] === undefined && (value as Record<string, any>)['wallet_id'] === undefined)) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('syncStatus' in (value as Record<string, any>)) && !('sync_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['syncStatus'] === undefined && (value as Record<string, any>)['sync_status'] === undefined)) return false;
    return true;
}

export function WalletFromJSON(json: any): Wallet {
    return WalletFromJSONTyped(json, false);
}

export function WalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wallet {
    if (json == null) {
        return json;
    }
    return {
        
        'walletId': json['wallet_id'],
        'accounts': ((json['accounts'] as Array<any>).map(WalletAccountFromJSON)),
        'createdAt': (new Date(json['created_at'])),
        'syncStatus': SyncStatusFromJSON(json['sync_status']),
    };
}

export function WalletToJSON(json: any): Wallet {
    return WalletToJSONTyped(json, false);
}

export function WalletToJSONTyped(value?: Wallet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wallet_id': value['walletId'],
        'accounts': ((value['accounts'] as Array<any>).map(WalletAccountToJSON)),
        'created_at': value['createdAt'].toISOString(),
        'sync_status': SyncStatusToJSON(value['syncStatus']),
    };
}

