/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletChallenge
 */
export interface WalletChallenge {
    /**
     * Stateless HMAC challenge to bind into the next /sync proof
     * @type {string}
     * @memberof WalletChallenge
     */
    challenge: string;
    /**
     * 
     * @type {Date}
     * @memberof WalletChallenge
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the WalletChallenge interface.
 */
export function instanceOfWalletChallenge(value: object): value is WalletChallenge {
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if ((!('expiresAt' in (value as Record<string, any>)) && !('expires_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiresAt'] === undefined && (value as Record<string, any>)['expires_at'] === undefined)) return false;
    return true;
}

export function WalletChallengeFromJSON(json: any): WalletChallenge {
    return WalletChallengeFromJSONTyped(json, false);
}

export function WalletChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletChallenge {
    if (json == null) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'expiresAt': (new Date(json['expires_at'])),
    };
}

export function WalletChallengeToJSON(json: any): WalletChallenge {
    return WalletChallengeToJSONTyped(json, false);
}

export function WalletChallengeToJSONTyped(value?: WalletChallenge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'expires_at': value['expiresAt'].toISOString(),
    };
}

