/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    CalculateSwap400Response,
    CalculateSwap500Response,
    CreateCrossSwapQuoteRequest,
    CrossSwapAsset,
    CrossSwapAssets,
    CrossSwapExecution,
    CrossSwapPrepare,
    CrossSwapQuote,
    CrossSwapSubmit,
    PrepareCrossSwapRouteRequest,
    SubmitCrossSwapPayloadRequest,
} from '../models/index';

export interface CreateCrossSwapQuoteOperationRequest {
    createCrossSwapQuoteRequest: CreateCrossSwapQuoteRequest;
}

export interface GetCrossSwapAssetRequest {
    assetId: string;
}

export interface GetCrossSwapExecutionRequest {
    executionId: string;
}

export interface ListCrossSwapAssetsRequest {
    q?: string;
    limit?: number;
}

export interface PrepareCrossSwapRouteOperationRequest {
    routeId: string;
    prepareCrossSwapRouteRequest?: PrepareCrossSwapRouteRequest;
}

export interface SubmitCrossSwapPayloadOperationRequest {
    payloadId: string;
    submitCrossSwapPayloadRequest: SubmitCrossSwapPayloadRequest;
}

/**
 * CrosschainApi - interface
 * 
 * @export
 * @interface CrosschainApiInterface
 */
export interface CrosschainApiInterface {
    /**
     * Creates request options for createCrossSwapQuote without sending the request
     * @param {CreateCrossSwapQuoteRequest} createCrossSwapQuoteRequest Cross-chain swap quote request
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    createCrossSwapQuoteRequestOpts(requestParameters: CreateCrossSwapQuoteOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create cross-chain swap quote
     * @param {CreateCrossSwapQuoteRequest} createCrossSwapQuoteRequest Cross-chain swap quote request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    createCrossSwapQuoteRaw(requestParameters: CreateCrossSwapQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapQuote>>;

    /**
     * Create cross-chain swap quote
     */
    createCrossSwapQuote(requestParameters: CreateCrossSwapQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapQuote>;

    /**
     * Creates request options for getCrossSwapAsset without sending the request
     * @param {string} assetId Internal asset_id, e.g. &#x60;ton/mainnet/coin&#x60; or &#x60;eth/mainnet/erc-20/0x...&#x60;
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    getCrossSwapAssetRequestOpts(requestParameters: GetCrossSwapAssetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Look up a single cross-chain asset by AssetID
     * @param {string} assetId Internal asset_id, e.g. &#x60;ton/mainnet/coin&#x60; or &#x60;eth/mainnet/erc-20/0x...&#x60;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    getCrossSwapAssetRaw(requestParameters: GetCrossSwapAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapAsset>>;

    /**
     * Look up a single cross-chain asset by AssetID
     */
    getCrossSwapAsset(requestParameters: GetCrossSwapAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapAsset>;

    /**
     * Creates request options for getCrossSwapExecution without sending the request
     * @param {string} executionId Execution identifier
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    getCrossSwapExecutionRequestOpts(requestParameters: GetCrossSwapExecutionRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get execution status
     * @param {string} executionId Execution identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    getCrossSwapExecutionRaw(requestParameters: GetCrossSwapExecutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapExecution>>;

    /**
     * Get execution status
     */
    getCrossSwapExecution(requestParameters: GetCrossSwapExecutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapExecution>;

    /**
     * Creates request options for listCrossSwapAssets without sending the request
     * @param {string} [q] Free-text query matched against Symbol and Name (case-insensitive). Whitespace is trimmed. Empty/missing returns the full list
     * @param {number} [limit] Maximum number of results. When &#x60;q&#x60; is set the server applies an internal default of 50 if omitted; when listing the full snapshot, omitting &#x60;limit&#x60; returns everything. Hard-capped at 1000
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    listCrossSwapAssetsRequestOpts(requestParameters: ListCrossSwapAssetsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List supported cross-chain assets
     * @param {string} [q] Free-text query matched against Symbol and Name (case-insensitive). Whitespace is trimmed. Empty/missing returns the full list
     * @param {number} [limit] Maximum number of results. When &#x60;q&#x60; is set the server applies an internal default of 50 if omitted; when listing the full snapshot, omitting &#x60;limit&#x60; returns everything. Hard-capped at 1000
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    listCrossSwapAssetsRaw(requestParameters: ListCrossSwapAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapAssets>>;

    /**
     * List supported cross-chain assets
     */
    listCrossSwapAssets(requestParameters: ListCrossSwapAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapAssets>;

    /**
     * Creates request options for prepareCrossSwapRoute without sending the request
     * @param {string} routeId Route identifier
     * @param {PrepareCrossSwapRouteRequest} [prepareCrossSwapRouteRequest] Optional flags controlling how the route is prepared
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    prepareCrossSwapRouteRequestOpts(requestParameters: PrepareCrossSwapRouteOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Prepare selected route
     * @param {string} routeId Route identifier
     * @param {PrepareCrossSwapRouteRequest} [prepareCrossSwapRouteRequest] Optional flags controlling how the route is prepared
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    prepareCrossSwapRouteRaw(requestParameters: PrepareCrossSwapRouteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapPrepare>>;

    /**
     * Prepare selected route
     */
    prepareCrossSwapRoute(requestParameters: PrepareCrossSwapRouteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapPrepare>;

    /**
     * Creates request options for submitCrossSwapPayload without sending the request
     * @param {string} payloadId Signing payload identifier
     * @param {SubmitCrossSwapPayloadRequest} submitCrossSwapPayloadRequest Submit a signed payload for broadcasting
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    submitCrossSwapPayloadRequestOpts(requestParameters: SubmitCrossSwapPayloadOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Submit signed payload
     * @param {string} payloadId Signing payload identifier
     * @param {SubmitCrossSwapPayloadRequest} submitCrossSwapPayloadRequest Submit a signed payload for broadcasting
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CrosschainApiInterface
     */
    submitCrossSwapPayloadRaw(requestParameters: SubmitCrossSwapPayloadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapSubmit>>;

    /**
     * Submit signed payload
     */
    submitCrossSwapPayload(requestParameters: SubmitCrossSwapPayloadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapSubmit>;

}

/**
 * 
 */
export class CrosschainApi extends runtime.BaseAPI implements CrosschainApiInterface {

    /**
     * Creates request options for createCrossSwapQuote without sending the request
     */
    async createCrossSwapQuoteRequestOpts(requestParameters: CreateCrossSwapQuoteOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createCrossSwapQuoteRequest'] == null) {
            throw new runtime.RequiredError(
                'createCrossSwapQuoteRequest',
                'Required parameter "createCrossSwapQuoteRequest" was null or undefined when calling createCrossSwapQuote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/crosschain/quotes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createCrossSwapQuoteRequest'],
        };
    }

    /**
     * Create cross-chain swap quote
     */
    async createCrossSwapQuoteRaw(requestParameters: CreateCrossSwapQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapQuote>> {
        const requestOptions = await this.createCrossSwapQuoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create cross-chain swap quote
     */
    async createCrossSwapQuote(requestParameters: CreateCrossSwapQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapQuote> {
        const response = await this.createCrossSwapQuoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCrossSwapAsset without sending the request
     */
    async getCrossSwapAssetRequestOpts(requestParameters: GetCrossSwapAssetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['assetId'] == null) {
            throw new runtime.RequiredError(
                'assetId',
                'Required parameter "assetId" was null or undefined when calling getCrossSwapAsset().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['assetId'] != null) {
            queryParameters['assetId'] = requestParameters['assetId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/crosschain/asset`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Look up a single cross-chain asset by AssetID
     */
    async getCrossSwapAssetRaw(requestParameters: GetCrossSwapAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapAsset>> {
        const requestOptions = await this.getCrossSwapAssetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Look up a single cross-chain asset by AssetID
     */
    async getCrossSwapAsset(requestParameters: GetCrossSwapAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapAsset> {
        const response = await this.getCrossSwapAssetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCrossSwapExecution without sending the request
     */
    async getCrossSwapExecutionRequestOpts(requestParameters: GetCrossSwapExecutionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['executionId'] == null) {
            throw new runtime.RequiredError(
                'executionId',
                'Required parameter "executionId" was null or undefined when calling getCrossSwapExecution().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/crosschain/executions/{execution_id}`;
        urlPath = urlPath.replace('{execution_id}', encodeURIComponent(String(requestParameters['executionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get execution status
     */
    async getCrossSwapExecutionRaw(requestParameters: GetCrossSwapExecutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapExecution>> {
        const requestOptions = await this.getCrossSwapExecutionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get execution status
     */
    async getCrossSwapExecution(requestParameters: GetCrossSwapExecutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapExecution> {
        const response = await this.getCrossSwapExecutionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCrossSwapAssets without sending the request
     */
    async listCrossSwapAssetsRequestOpts(requestParameters: ListCrossSwapAssetsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/crosschain/assets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List supported cross-chain assets
     */
    async listCrossSwapAssetsRaw(requestParameters: ListCrossSwapAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapAssets>> {
        const requestOptions = await this.listCrossSwapAssetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List supported cross-chain assets
     */
    async listCrossSwapAssets(requestParameters: ListCrossSwapAssetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapAssets> {
        const response = await this.listCrossSwapAssetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for prepareCrossSwapRoute without sending the request
     */
    async prepareCrossSwapRouteRequestOpts(requestParameters: PrepareCrossSwapRouteOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling prepareCrossSwapRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/crosschain/routes/{route_id}/prepare`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['prepareCrossSwapRouteRequest'],
        };
    }

    /**
     * Prepare selected route
     */
    async prepareCrossSwapRouteRaw(requestParameters: PrepareCrossSwapRouteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapPrepare>> {
        const requestOptions = await this.prepareCrossSwapRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Prepare selected route
     */
    async prepareCrossSwapRoute(requestParameters: PrepareCrossSwapRouteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapPrepare> {
        const response = await this.prepareCrossSwapRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitCrossSwapPayload without sending the request
     */
    async submitCrossSwapPayloadRequestOpts(requestParameters: SubmitCrossSwapPayloadOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['payloadId'] == null) {
            throw new runtime.RequiredError(
                'payloadId',
                'Required parameter "payloadId" was null or undefined when calling submitCrossSwapPayload().'
            );
        }

        if (requestParameters['submitCrossSwapPayloadRequest'] == null) {
            throw new runtime.RequiredError(
                'submitCrossSwapPayloadRequest',
                'Required parameter "submitCrossSwapPayloadRequest" was null or undefined when calling submitCrossSwapPayload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/crosschain/payloads/{payload_id}/submit`;
        urlPath = urlPath.replace('{payload_id}', encodeURIComponent(String(requestParameters['payloadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['submitCrossSwapPayloadRequest'],
        };
    }

    /**
     * Submit signed payload
     */
    async submitCrossSwapPayloadRaw(requestParameters: SubmitCrossSwapPayloadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossSwapSubmit>> {
        const requestOptions = await this.submitCrossSwapPayloadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Submit signed payload
     */
    async submitCrossSwapPayload(requestParameters: SubmitCrossSwapPayloadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossSwapSubmit> {
        const response = await this.submitCrossSwapPayloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
