/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    CalculateSwap400Response,
    CalculateSwap500Response,
    CreateExchangeRequest,
    ExchangeCalculateRequest,
    ExchangeCalculation,
    ExchangeCurrencies,
    ExchangeDirection,
    ExchangeFlow,
    ExchangeLayout,
    ExchangeMerchantInfo,
    ExchangePairs,
    ExchangePaymentMethod,
    ExchangeResult,
    Platform,
} from '../models/index';

export interface CreateExchangeOperationRequest {
    createExchangeRequest: CreateExchangeRequest;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
}

export interface ExchangeCalculateOperationRequest {
    exchangeCalculateRequest: ExchangeCalculateRequest;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
}

export interface GetExchangeCurrenciesRequest {
    country?: string;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
    direction?: ExchangeDirection;
}

export interface GetExchangeLayoutRequest {
    flow: ExchangeFlow;
    currency?: string;
    lang?: string;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    platform?: Platform;
}

export interface GetExchangeMerchantsRequest {
    lang?: string;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
}

export interface GetExchangePairsRequest {
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    direction?: ExchangeDirection;
    fiat?: string;
    crypto?: string;
    network?: string;
    platform?: Platform;
    build?: string;
}

export interface GetExchangePaymentMethodsRequest {
    country?: string;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
    currency?: string;
}

/**
 * ExchangeApi - interface
 * 
 * @export
 * @interface ExchangeApiInterface
 */
export interface ExchangeApiInterface {
    /**
     * Creates request options for createExchange without sending the request
     * @param {CreateExchangeRequest} createExchangeRequest Crypto-to-crypto exchange parameters
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    createExchangeRequestOpts(requestParameters: CreateExchangeOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a crypto-to-crypto exchange
     * @summary Create crypto-to-crypto exchange
     * @param {CreateExchangeRequest} createExchangeRequest Crypto-to-crypto exchange parameters
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    createExchangeRaw(requestParameters: CreateExchangeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeResult>>;

    /**
     * Create a crypto-to-crypto exchange
     * Create crypto-to-crypto exchange
     */
    createExchange(requestParameters: CreateExchangeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeResult>;

    /**
     * Creates request options for exchangeCalculate without sending the request
     * @param {ExchangeCalculateRequest} exchangeCalculateRequest Exchange rate calculation parameters
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    exchangeCalculateRequestOpts(requestParameters: ExchangeCalculateOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Get exchange rates from all available merchants
     * @summary Calculate exchange rates
     * @param {ExchangeCalculateRequest} exchangeCalculateRequest Exchange rate calculation parameters
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    exchangeCalculateRaw(requestParameters: ExchangeCalculateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeCalculation>>;

    /**
     * Get exchange rates from all available merchants
     * Calculate exchange rates
     * @deprecated
     */
    exchangeCalculate(requestParameters: ExchangeCalculateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeCalculation>;

    /**
     * Creates request options for getExchangeCurrencies without sending the request
     * @param {string} [country] User country code (ISO 3166-1 alpha-2). Deprecated: use device_country_code and store_country_code instead
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {ExchangeDirection} [direction] Trade direction
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangeCurrenciesRequestOpts(requestParameters: GetExchangeCurrenciesRequest): Promise<runtime.RequestOpts>;

    /**
     * Get available currencies, merchants and trading pairs
     * @summary Get currencies
     * @param {string} [country] User country code (ISO 3166-1 alpha-2). Deprecated: use device_country_code and store_country_code instead
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {ExchangeDirection} [direction] Trade direction
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangeCurrenciesRaw(requestParameters: GetExchangeCurrenciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeCurrencies>>;

    /**
     * Get available currencies, merchants and trading pairs
     * Get currencies
     * @deprecated
     */
    getExchangeCurrencies(requestParameters: GetExchangeCurrenciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeCurrencies>;

    /**
     * Creates request options for getExchangeLayout without sending the request
     * @param {ExchangeFlow} flow Flow type: deposit (buy crypto) or withdraw (sell crypto)
     * @param {string} [currency] Fiat currency code (e.g. EUR, USD)
     * @param {string} [lang] Language code
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {Platform} [platform] User device platform
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangeLayoutRequestOpts(requestParameters: GetExchangeLayoutRequest): Promise<runtime.RequestOpts>;

    /**
     * Get available crypto assets with cash and crypto methods for deposit or withdraw
     * @summary Get deposit/withdraw assets and methods
     * @param {ExchangeFlow} flow Flow type: deposit (buy crypto) or withdraw (sell crypto)
     * @param {string} [currency] Fiat currency code (e.g. EUR, USD)
     * @param {string} [lang] Language code
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {Platform} [platform] User device platform
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangeLayoutRaw(requestParameters: GetExchangeLayoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeLayout>>;

    /**
     * Get available crypto assets with cash and crypto methods for deposit or withdraw
     * Get deposit/withdraw assets and methods
     * @deprecated
     */
    getExchangeLayout(requestParameters: GetExchangeLayoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeLayout>;

    /**
     * Creates request options for getExchangeMerchants without sending the request
     * @param {string} [lang] Language code
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangeMerchantsRequestOpts(requestParameters: GetExchangeMerchantsRequest): Promise<runtime.RequestOpts>;

    /**
     * Get merchant information for display
     * @summary Get merchants
     * @param {string} [lang] Language code
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangeMerchantsRaw(requestParameters: GetExchangeMerchantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExchangeMerchantInfo>>>;

    /**
     * Get merchant information for display
     * Get merchants
     */
    getExchangeMerchants(requestParameters: GetExchangeMerchantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExchangeMerchantInfo>>;

    /**
     * Creates request options for getExchangePairs without sending the request
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {ExchangeDirection} [direction] Trade direction
     * @param {string} [fiat] Fiat currency filter (e.g. EUR, USD)
     * @param {string} [crypto] Crypto currency filter (e.g. TON, USDT)
     * @param {string} [network] Crypto network filter (e.g. native, jetton)
     * @param {Platform} [platform] User device platform
     * @param {string} [build] App build version
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangePairsRequestOpts(requestParameters: GetExchangePairsRequest): Promise<runtime.RequestOpts>;

    /**
     * Get available trading pairs with filtering
     * @summary Get trading pairs
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {ExchangeDirection} [direction] Trade direction
     * @param {string} [fiat] Fiat currency filter (e.g. EUR, USD)
     * @param {string} [crypto] Crypto currency filter (e.g. TON, USDT)
     * @param {string} [network] Crypto network filter (e.g. native, jetton)
     * @param {Platform} [platform] User device platform
     * @param {string} [build] App build version
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangePairsRaw(requestParameters: GetExchangePairsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangePairs>>;

    /**
     * Get available trading pairs with filtering
     * Get trading pairs
     * @deprecated
     */
    getExchangePairs(requestParameters: GetExchangePairsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangePairs>;

    /**
     * Creates request options for getExchangePaymentMethods without sending the request
     * @param {string} [country] User country code (ISO 3166-1 alpha-2). Deprecated: use device_country_code and store_country_code instead
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [currency] Fiat currency code (e.g. EUR, USD)
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangePaymentMethodsRequestOpts(requestParameters: GetExchangePaymentMethodsRequest): Promise<runtime.RequestOpts>;

    /**
     * Get available payment methods by currency and country
     * @summary Get payment methods
     * @param {string} [country] User country code (ISO 3166-1 alpha-2). Deprecated: use device_country_code and store_country_code instead
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [currency] Fiat currency code (e.g. EUR, USD)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExchangeApiInterface
     */
    getExchangePaymentMethodsRaw(requestParameters: GetExchangePaymentMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExchangePaymentMethod>>>;

    /**
     * Get available payment methods by currency and country
     * Get payment methods
     */
    getExchangePaymentMethods(requestParameters: GetExchangePaymentMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExchangePaymentMethod>>;

}

/**
 * 
 */
export class ExchangeApi extends runtime.BaseAPI implements ExchangeApiInterface {

    /**
     * Creates request options for createExchange without sending the request
     */
    async createExchangeRequestOpts(requestParameters: CreateExchangeOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createExchangeRequest'] == null) {
            throw new runtime.RequiredError(
                'createExchangeRequest',
                'Required parameter "createExchangeRequest" was null or undefined when calling createExchange().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/onramp/exchange`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createExchangeRequest'],
        };
    }

    /**
     * Create a crypto-to-crypto exchange
     * Create crypto-to-crypto exchange
     */
    async createExchangeRaw(requestParameters: CreateExchangeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeResult>> {
        const requestOptions = await this.createExchangeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create a crypto-to-crypto exchange
     * Create crypto-to-crypto exchange
     */
    async createExchange(requestParameters: CreateExchangeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeResult> {
        const response = await this.createExchangeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for exchangeCalculate without sending the request
     * @deprecated
     */
    async exchangeCalculateRequestOpts(requestParameters: ExchangeCalculateOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['exchangeCalculateRequest'] == null) {
            throw new runtime.RequiredError(
                'exchangeCalculateRequest',
                'Required parameter "exchangeCalculateRequest" was null or undefined when calling exchangeCalculate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/onramp/calculate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['exchangeCalculateRequest'],
        };
    }

    /**
     * Get exchange rates from all available merchants
     * Calculate exchange rates
     * @deprecated
     */
    async exchangeCalculateRaw(requestParameters: ExchangeCalculateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeCalculation>> {
        const requestOptions = await this.exchangeCalculateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get exchange rates from all available merchants
     * Calculate exchange rates
     * @deprecated
     */
    async exchangeCalculate(requestParameters: ExchangeCalculateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeCalculation> {
        const response = await this.exchangeCalculateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExchangeCurrencies without sending the request
     * @deprecated
     */
    async getExchangeCurrenciesRequestOpts(requestParameters: GetExchangeCurrenciesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/onramp/currencies`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get available currencies, merchants and trading pairs
     * Get currencies
     * @deprecated
     */
    async getExchangeCurrenciesRaw(requestParameters: GetExchangeCurrenciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeCurrencies>> {
        const requestOptions = await this.getExchangeCurrenciesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get available currencies, merchants and trading pairs
     * Get currencies
     * @deprecated
     */
    async getExchangeCurrencies(requestParameters: GetExchangeCurrenciesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeCurrencies> {
        const response = await this.getExchangeCurrenciesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExchangeLayout without sending the request
     * @deprecated
     */
    async getExchangeLayoutRequestOpts(requestParameters: GetExchangeLayoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['flow'] == null) {
            throw new runtime.RequiredError(
                'flow',
                'Required parameter "flow" was null or undefined when calling getExchangeLayout().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['flow'] != null) {
            queryParameters['flow'] = requestParameters['flow'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/onramp/layout`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get available crypto assets with cash and crypto methods for deposit or withdraw
     * Get deposit/withdraw assets and methods
     * @deprecated
     */
    async getExchangeLayoutRaw(requestParameters: GetExchangeLayoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeLayout>> {
        const requestOptions = await this.getExchangeLayoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get available crypto assets with cash and crypto methods for deposit or withdraw
     * Get deposit/withdraw assets and methods
     * @deprecated
     */
    async getExchangeLayout(requestParameters: GetExchangeLayoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeLayout> {
        const response = await this.getExchangeLayoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExchangeMerchants without sending the request
     */
    async getExchangeMerchantsRequestOpts(requestParameters: GetExchangeMerchantsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/onramp/merchants`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get merchant information for display
     * Get merchants
     */
    async getExchangeMerchantsRaw(requestParameters: GetExchangeMerchantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExchangeMerchantInfo>>> {
        const requestOptions = await this.getExchangeMerchantsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get merchant information for display
     * Get merchants
     */
    async getExchangeMerchants(requestParameters: GetExchangeMerchantsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExchangeMerchantInfo>> {
        const response = await this.getExchangeMerchantsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExchangePairs without sending the request
     * @deprecated
     */
    async getExchangePairsRequestOpts(requestParameters: GetExchangePairsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['fiat'] != null) {
            queryParameters['fiat'] = requestParameters['fiat'];
        }

        if (requestParameters['crypto'] != null) {
            queryParameters['crypto'] = requestParameters['crypto'];
        }

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/onramp/pairs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get available trading pairs with filtering
     * Get trading pairs
     * @deprecated
     */
    async getExchangePairsRaw(requestParameters: GetExchangePairsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangePairs>> {
        const requestOptions = await this.getExchangePairsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get available trading pairs with filtering
     * Get trading pairs
     * @deprecated
     */
    async getExchangePairs(requestParameters: GetExchangePairsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangePairs> {
        const response = await this.getExchangePairsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExchangePaymentMethods without sending the request
     */
    async getExchangePaymentMethodsRequestOpts(requestParameters: GetExchangePaymentMethodsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/onramp/payment_methods`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get available payment methods by currency and country
     * Get payment methods
     */
    async getExchangePaymentMethodsRaw(requestParameters: GetExchangePaymentMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExchangePaymentMethod>>> {
        const requestOptions = await this.getExchangePaymentMethodsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get available payment methods by currency and country
     * Get payment methods
     */
    async getExchangePaymentMethods(requestParameters: GetExchangePaymentMethodsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExchangePaymentMethod>> {
        const response = await this.getExchangePaymentMethodsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
