/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    CalculateSwap400Response,
    CalculateSwap500Response,
    CreateOfframpOrderRequest,
    ExchangePaymentMethodType,
    OfframpConfiguration,
    OfframpOrder,
    OfframpQuoteRequest,
    OfframpQuotes,
    Platform,
} from '../models/index';

export interface CreateOfframpOrderOperationRequest {
    createOfframpOrderRequest: CreateOfframpOrderRequest;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
    idempotencyKey?: string;
}

export interface GetOfframpConfigurationRequest {
    sourceChain?: string;
    fiat?: string;
    payoutMethod?: ExchangePaymentMethodType;
    country?: string;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
    lang?: string;
    ifNoneMatch?: string;
}

export interface GetOfframpOrderRequest {
    orderId: string;
}

export interface OfframpQuoteOperationRequest {
    offrampQuoteRequest: OfframpQuoteRequest;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
}

/**
 * OfframpApi - interface
 * 
 * @export
 * @interface OfframpApiInterface
 */
export interface OfframpApiInterface {
    /**
     * Creates request options for createOfframpOrder without sending the request
     * @param {CreateOfframpOrderRequest} createOfframpOrderRequest Create off-ramp order. Use &#x60;Idempotency-Key&#x60; for safe retry
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [idempotencyKey] UUID v4 for safe retry
     * @throws {RequiredError}
     * @memberof OfframpApiInterface
     */
    createOfframpOrderRequestOpts(requestParameters: CreateOfframpOrderOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create off-ramp transaction
     * @param {CreateOfframpOrderRequest} createOfframpOrderRequest Create off-ramp order. Use &#x60;Idempotency-Key&#x60; for safe retry
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [idempotencyKey] UUID v4 for safe retry
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfframpApiInterface
     */
    createOfframpOrderRaw(requestParameters: CreateOfframpOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfframpOrder>>;

    /**
     * Create off-ramp transaction
     */
    createOfframpOrder(requestParameters: CreateOfframpOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfframpOrder>;

    /**
     * Creates request options for getOfframpConfiguration without sending the request
     * @param {string} [sourceChain] Internal chain id, e.g. &#x60;eth/mainnet&#x60;
     * @param {string} [fiat] Target fiat (ISO 4217)
     * @param {ExchangePaymentMethodType} [payoutMethod] 
     * @param {string} [country] User country code (ISO 3166-1 alpha-2). Deprecated: use device_country_code and store_country_code instead
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [lang] Language code
     * @param {string} [ifNoneMatch] ETag from a prior response
     * @throws {RequiredError}
     * @memberof OfframpApiInterface
     */
    getOfframpConfigurationRequestOpts(requestParameters: GetOfframpConfigurationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List supported off-ramp tuples
     * @param {string} [sourceChain] Internal chain id, e.g. &#x60;eth/mainnet&#x60;
     * @param {string} [fiat] Target fiat (ISO 4217)
     * @param {ExchangePaymentMethodType} [payoutMethod] 
     * @param {string} [country] User country code (ISO 3166-1 alpha-2). Deprecated: use device_country_code and store_country_code instead
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [lang] Language code
     * @param {string} [ifNoneMatch] ETag from a prior response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfframpApiInterface
     */
    getOfframpConfigurationRaw(requestParameters: GetOfframpConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfframpConfiguration>>;

    /**
     * List supported off-ramp tuples
     */
    getOfframpConfiguration(requestParameters: GetOfframpConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfframpConfiguration>;

    /**
     * Creates request options for getOfframpOrder without sending the request
     * @param {string} orderId 
     * @throws {RequiredError}
     * @memberof OfframpApiInterface
     */
    getOfframpOrderRequestOpts(requestParameters: GetOfframpOrderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get off-ramp order status
     * @param {string} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfframpApiInterface
     */
    getOfframpOrderRaw(requestParameters: GetOfframpOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfframpOrder>>;

    /**
     * Get off-ramp order status
     */
    getOfframpOrder(requestParameters: GetOfframpOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfframpOrder>;

    /**
     * Creates request options for offrampQuote without sending the request
     * @param {OfframpQuoteRequest} offrampQuoteRequest Off-ramp quote request
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @throws {RequiredError}
     * @memberof OfframpApiInterface
     */
    offrampQuoteRequestOpts(requestParameters: OfframpQuoteOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Multi-merchant off-ramp quote
     * @param {OfframpQuoteRequest} offrampQuoteRequest Off-ramp quote request
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfframpApiInterface
     */
    offrampQuoteRaw(requestParameters: OfframpQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfframpQuotes>>;

    /**
     * Multi-merchant off-ramp quote
     */
    offrampQuote(requestParameters: OfframpQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfframpQuotes>;

}

/**
 * 
 */
export class OfframpApi extends runtime.BaseAPI implements OfframpApiInterface {

    /**
     * Creates request options for createOfframpOrder without sending the request
     */
    async createOfframpOrderRequestOpts(requestParameters: CreateOfframpOrderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createOfframpOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'createOfframpOrderRequest',
                'Required parameter "createOfframpOrderRequest" was null or undefined when calling createOfframpOrder().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/v2/offramp/orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createOfframpOrderRequest'],
        };
    }

    /**
     * Create off-ramp transaction
     */
    async createOfframpOrderRaw(requestParameters: CreateOfframpOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfframpOrder>> {
        const requestOptions = await this.createOfframpOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create off-ramp transaction
     */
    async createOfframpOrder(requestParameters: CreateOfframpOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfframpOrder> {
        const response = await this.createOfframpOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOfframpConfiguration without sending the request
     */
    async getOfframpConfigurationRequestOpts(requestParameters: GetOfframpConfigurationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['sourceChain'] != null) {
            queryParameters['source_chain'] = requestParameters['sourceChain'];
        }

        if (requestParameters['fiat'] != null) {
            queryParameters['fiat'] = requestParameters['fiat'];
        }

        if (requestParameters['payoutMethod'] != null) {
            queryParameters['payout_method'] = requestParameters['payoutMethod'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }


        let urlPath = `/v2/offramp/configuration`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List supported off-ramp tuples
     */
    async getOfframpConfigurationRaw(requestParameters: GetOfframpConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfframpConfiguration>> {
        const requestOptions = await this.getOfframpConfigurationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List supported off-ramp tuples
     */
    async getOfframpConfiguration(requestParameters: GetOfframpConfigurationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfframpConfiguration> {
        const response = await this.getOfframpConfigurationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOfframpOrder without sending the request
     */
    async getOfframpOrderRequestOpts(requestParameters: GetOfframpOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getOfframpOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/offramp/orders/{order_id}`;
        urlPath = urlPath.replace('{order_id}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get off-ramp order status
     */
    async getOfframpOrderRaw(requestParameters: GetOfframpOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfframpOrder>> {
        const requestOptions = await this.getOfframpOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get off-ramp order status
     */
    async getOfframpOrder(requestParameters: GetOfframpOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfframpOrder> {
        const response = await this.getOfframpOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for offrampQuote without sending the request
     */
    async offrampQuoteRequestOpts(requestParameters: OfframpQuoteOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['offrampQuoteRequest'] == null) {
            throw new runtime.RequiredError(
                'offrampQuoteRequest',
                'Required parameter "offrampQuoteRequest" was null or undefined when calling offrampQuote().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/offramp/quote`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['offrampQuoteRequest'],
        };
    }

    /**
     * Multi-merchant off-ramp quote
     */
    async offrampQuoteRaw(requestParameters: OfframpQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OfframpQuotes>> {
        const requestOptions = await this.offrampQuoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Multi-merchant off-ramp quote
     */
    async offrampQuote(requestParameters: OfframpQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OfframpQuotes> {
        const response = await this.offrampQuoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
