/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    CalculateSwap400Response,
    CalculateSwap500Response,
    CreateOnrampOrderRequest,
    ExchangePaymentMethodType,
    OnrampConfiguration,
    OnrampOrder,
    OnrampQuoteRequest,
    OnrampQuotes,
    Platform,
} from '../models/index';

export interface CreateOnrampOrderOperationRequest {
    createOnrampOrderRequest: CreateOnrampOrderRequest;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
    idempotencyKey?: string;
}

export interface GetOnrampConfigurationRequest {
    destinationChain?: string;
    fiat?: string;
    paymentMethod?: ExchangePaymentMethodType;
    country?: string;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
    lang?: string;
    ifNoneMatch?: string;
}

export interface GetOnrampOrderRequest {
    orderId: string;
}

export interface OnrampQuoteOperationRequest {
    onrampQuoteRequest: OnrampQuoteRequest;
    deviceCountryCode?: string;
    storeCountryCode?: string;
    simCountry?: string;
    timezone?: string;
    isVpnActive?: boolean;
    build?: string;
    platform?: Platform;
}

/**
 * OnrampApi - interface
 * 
 * @export
 * @interface OnrampApiInterface
 */
export interface OnrampApiInterface {
    /**
     * Creates request options for createOnrampOrder without sending the request
     * @param {CreateOnrampOrderRequest} createOnrampOrderRequest Create on-ramp order. Use &#x60;Idempotency-Key&#x60; for safe retry
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [idempotencyKey] UUID v4 for safe retry
     * @throws {RequiredError}
     * @memberof OnrampApiInterface
     */
    createOnrampOrderRequestOpts(requestParameters: CreateOnrampOrderOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create on-ramp transaction
     * @param {CreateOnrampOrderRequest} createOnrampOrderRequest Create on-ramp order. Use &#x60;Idempotency-Key&#x60; for safe retry
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [idempotencyKey] UUID v4 for safe retry
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnrampApiInterface
     */
    createOnrampOrderRaw(requestParameters: CreateOnrampOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnrampOrder>>;

    /**
     * Create on-ramp transaction
     */
    createOnrampOrder(requestParameters: CreateOnrampOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnrampOrder>;

    /**
     * Creates request options for getOnrampConfiguration without sending the request
     * @param {string} [destinationChain] Internal chain id, e.g. &#x60;eth/mainnet&#x60;
     * @param {string} [fiat] Source fiat (ISO 4217)
     * @param {ExchangePaymentMethodType} [paymentMethod] 
     * @param {string} [country] User country code (ISO 3166-1 alpha-2). Deprecated: use device_country_code and store_country_code instead
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [lang] Language code
     * @param {string} [ifNoneMatch] ETag from a prior response
     * @throws {RequiredError}
     * @memberof OnrampApiInterface
     */
    getOnrampConfigurationRequestOpts(requestParameters: GetOnrampConfigurationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List supported on-ramp tuples
     * @param {string} [destinationChain] Internal chain id, e.g. &#x60;eth/mainnet&#x60;
     * @param {string} [fiat] Source fiat (ISO 4217)
     * @param {ExchangePaymentMethodType} [paymentMethod] 
     * @param {string} [country] User country code (ISO 3166-1 alpha-2). Deprecated: use device_country_code and store_country_code instead
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {string} [lang] Language code
     * @param {string} [ifNoneMatch] ETag from a prior response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnrampApiInterface
     */
    getOnrampConfigurationRaw(requestParameters: GetOnrampConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnrampConfiguration>>;

    /**
     * List supported on-ramp tuples
     */
    getOnrampConfiguration(requestParameters: GetOnrampConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnrampConfiguration>;

    /**
     * Creates request options for getOnrampOrder without sending the request
     * @param {string} orderId 
     * @throws {RequiredError}
     * @memberof OnrampApiInterface
     */
    getOnrampOrderRequestOpts(requestParameters: GetOnrampOrderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get on-ramp order status
     * @param {string} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnrampApiInterface
     */
    getOnrampOrderRaw(requestParameters: GetOnrampOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnrampOrder>>;

    /**
     * Get on-ramp order status
     */
    getOnrampOrder(requestParameters: GetOnrampOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnrampOrder>;

    /**
     * Creates request options for onrampQuote without sending the request
     * @param {OnrampQuoteRequest} onrampQuoteRequest On-ramp quote request
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @throws {RequiredError}
     * @memberof OnrampApiInterface
     */
    onrampQuoteRequestOpts(requestParameters: OnrampQuoteOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Multi-merchant on-ramp quote
     * @param {OnrampQuoteRequest} onrampQuoteRequest On-ramp quote request
     * @param {string} [deviceCountryCode] Device country code (ISO 3166-1 alpha-2)
     * @param {string} [storeCountryCode] App Store country code (ISO 3166-1 alpha-2)
     * @param {string} [simCountry] SIM card country code (ISO 3166-1 alpha-2)
     * @param {string} [timezone] Device timezone (IANA format, e.g. Europe/Berlin)
     * @param {boolean} [isVpnActive] Whether VPN is currently active
     * @param {string} [build] App build version
     * @param {Platform} [platform] User device platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnrampApiInterface
     */
    onrampQuoteRaw(requestParameters: OnrampQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnrampQuotes>>;

    /**
     * Multi-merchant on-ramp quote
     */
    onrampQuote(requestParameters: OnrampQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnrampQuotes>;

}

/**
 * 
 */
export class OnrampApi extends runtime.BaseAPI implements OnrampApiInterface {

    /**
     * Creates request options for createOnrampOrder without sending the request
     */
    async createOnrampOrderRequestOpts(requestParameters: CreateOnrampOrderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createOnrampOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'createOnrampOrderRequest',
                'Required parameter "createOnrampOrderRequest" was null or undefined when calling createOnrampOrder().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/v2/onramp/orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createOnrampOrderRequest'],
        };
    }

    /**
     * Create on-ramp transaction
     */
    async createOnrampOrderRaw(requestParameters: CreateOnrampOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnrampOrder>> {
        const requestOptions = await this.createOnrampOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create on-ramp transaction
     */
    async createOnrampOrder(requestParameters: CreateOnrampOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnrampOrder> {
        const response = await this.createOnrampOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOnrampConfiguration without sending the request
     */
    async getOnrampConfigurationRequestOpts(requestParameters: GetOnrampConfigurationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['destinationChain'] != null) {
            queryParameters['destination_chain'] = requestParameters['destinationChain'];
        }

        if (requestParameters['fiat'] != null) {
            queryParameters['fiat'] = requestParameters['fiat'];
        }

        if (requestParameters['paymentMethod'] != null) {
            queryParameters['payment_method'] = requestParameters['paymentMethod'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }


        let urlPath = `/v2/onramp/configuration`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List supported on-ramp tuples
     */
    async getOnrampConfigurationRaw(requestParameters: GetOnrampConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnrampConfiguration>> {
        const requestOptions = await this.getOnrampConfigurationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List supported on-ramp tuples
     */
    async getOnrampConfiguration(requestParameters: GetOnrampConfigurationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnrampConfiguration> {
        const response = await this.getOnrampConfigurationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOnrampOrder without sending the request
     */
    async getOnrampOrderRequestOpts(requestParameters: GetOnrampOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getOnrampOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/onramp/orders/{order_id}`;
        urlPath = urlPath.replace('{order_id}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get on-ramp order status
     */
    async getOnrampOrderRaw(requestParameters: GetOnrampOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnrampOrder>> {
        const requestOptions = await this.getOnrampOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get on-ramp order status
     */
    async getOnrampOrder(requestParameters: GetOnrampOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnrampOrder> {
        const response = await this.getOnrampOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for onrampQuote without sending the request
     */
    async onrampQuoteRequestOpts(requestParameters: OnrampQuoteOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['onrampQuoteRequest'] == null) {
            throw new runtime.RequiredError(
                'onrampQuoteRequest',
                'Required parameter "onrampQuoteRequest" was null or undefined when calling onrampQuote().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deviceCountryCode'] != null) {
            queryParameters['device_country_code'] = requestParameters['deviceCountryCode'];
        }

        if (requestParameters['storeCountryCode'] != null) {
            queryParameters['store_country_code'] = requestParameters['storeCountryCode'];
        }

        if (requestParameters['simCountry'] != null) {
            queryParameters['sim_country'] = requestParameters['simCountry'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['isVpnActive'] != null) {
            queryParameters['is_vpn_active'] = requestParameters['isVpnActive'];
        }

        if (requestParameters['build'] != null) {
            queryParameters['build'] = requestParameters['build'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/onramp/quote`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['onrampQuoteRequest'],
        };
    }

    /**
     * Multi-merchant on-ramp quote
     */
    async onrampQuoteRaw(requestParameters: OnrampQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnrampQuotes>> {
        const requestOptions = await this.onrampQuoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Multi-merchant on-ramp quote
     */
    async onrampQuote(requestParameters: OnrampQuoteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnrampQuotes> {
        const response = await this.onrampQuoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
