/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    CalculateSwap400Response,
    CalculateSwap500Response,
    CreateP2PSessionRequest,
    P2PSessionResult,
} from '../models/index';

export interface CreateP2PSessionOperationRequest {
    createP2PSessionRequest: CreateP2PSessionRequest;
}

/**
 * P2pApi - interface
 * 
 * @export
 * @interface P2pApiInterface
 */
export interface P2pApiInterface {
    /**
     * Creates request options for createP2PSession without sending the request
     * @param {CreateP2PSessionRequest} createP2PSessionRequest P2P deeplink session parameters
     * @throws {RequiredError}
     * @memberof P2pApiInterface
     */
    createP2PSessionRequestOpts(requestParameters: CreateP2PSessionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a P2P exchange deeplink session
     * @summary Create P2P deeplink session
     * @param {CreateP2PSessionRequest} createP2PSessionRequest P2P deeplink session parameters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof P2pApiInterface
     */
    createP2PSessionRaw(requestParameters: CreateP2PSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<P2PSessionResult>>;

    /**
     * Create a P2P exchange deeplink session
     * Create P2P deeplink session
     */
    createP2PSession(requestParameters: CreateP2PSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<P2PSessionResult>;

}

/**
 * 
 */
export class P2pApi extends runtime.BaseAPI implements P2pApiInterface {

    /**
     * Creates request options for createP2PSession without sending the request
     */
    async createP2PSessionRequestOpts(requestParameters: CreateP2PSessionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createP2PSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createP2PSessionRequest',
                'Required parameter "createP2PSessionRequest" was null or undefined when calling createP2PSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/p2p/session`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createP2PSessionRequest'],
        };
    }

    /**
     * Create a P2P exchange deeplink session
     * Create P2P deeplink session
     */
    async createP2PSessionRaw(requestParameters: CreateP2PSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<P2PSessionResult>> {
        const requestOptions = await this.createP2PSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create a P2P exchange deeplink session
     * Create P2P deeplink session
     */
    async createP2PSession(requestParameters: CreateP2PSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<P2PSessionResult> {
        const response = await this.createP2PSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
