/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Chain,
    ChainFromJSON,
    ChainToJSON,
} from '../models/Chain';
import {
    type Healthcheck500Response,
    Healthcheck500ResponseFromJSON,
    Healthcheck500ResponseToJSON,
} from '../models/Healthcheck500Response';
import {
    type SearchAssets200Response,
    SearchAssets200ResponseFromJSON,
    SearchAssets200ResponseToJSON,
} from '../models/SearchAssets200Response';

export interface SearchAssetsRequest {
    currencies: Array<string>;
    sort: SearchAssetsSortEnum;
    chain?: Chain;
    search?: string;
    limit?: number;
    cursor?: string;
}

/**
 * AssetsApi - interface
 * 
 * @export
 * @interface AssetsApiInterface
 */
export interface AssetsApiInterface {
    /**
     * Creates request options for searchAssets without sending the request
     * @param {Array<string>} currencies Base currencies
     * @param {'market_cap' | 'volume'} sort Sort tokens by
     * @param {Chain} [chain] Filter by chain
     * @param {string} [search] Name or symbol of token
     * @param {number} [limit] Pagination limit
     * @param {string} [cursor] Cursor for pagination
     * @throws {RequiredError}
     * @memberof AssetsApiInterface
     */
    searchAssetsRequestOpts(requestParameters: SearchAssetsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get assets for an address on a chain
     * @param {Array<string>} currencies Base currencies
     * @param {'market_cap' | 'volume'} sort Sort tokens by
     * @param {Chain} [chain] Filter by chain
     * @param {string} [search] Name or symbol of token
     * @param {number} [limit] Pagination limit
     * @param {string} [cursor] Cursor for pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetsApiInterface
     */
    searchAssetsRaw(requestParameters: SearchAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchAssets200Response>>;

    /**
     * Get assets for an address on a chain
     */
    searchAssets(requestParameters: SearchAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchAssets200Response>;

}

/**
 * 
 */
export class AssetsApi extends runtime.BaseAPI implements AssetsApiInterface {

    /**
     * Creates request options for searchAssets without sending the request
     */
    async searchAssetsRequestOpts(requestParameters: SearchAssetsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currencies'] == null) {
            throw new runtime.RequiredError(
                'currencies',
                'Required parameter "currencies" was null or undefined when calling searchAssets().'
            );
        }

        if (requestParameters['sort'] == null) {
            throw new runtime.RequiredError(
                'sort',
                'Required parameter "sort" was null or undefined when calling searchAssets().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chain'] != null) {
            queryParameters['chain'] = requestParameters['chain'];
        }

        if (requestParameters['currencies'] != null) {
            queryParameters['currencies'] = requestParameters['currencies']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/assets/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get assets for an address on a chain
     */
    async searchAssetsRaw(requestParameters: SearchAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchAssets200Response>> {
        const requestOptions = await this.searchAssetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchAssets200ResponseFromJSON(jsonValue));
    }

    /**
     * Get assets for an address on a chain
     */
    async searchAssets(requestParameters: SearchAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchAssets200Response> {
        const response = await this.searchAssetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchAssetsSortEnum = {
    MarketCap: 'market_cap',
    Volume: 'volume'
} as const;
export type SearchAssetsSortEnum = typeof SearchAssetsSortEnum[keyof typeof SearchAssetsSortEnum];
