/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BroadcastTx200Response,
    BroadcastTx200ResponseFromJSON,
    BroadcastTx200ResponseToJSON,
} from '../models/BroadcastTx200Response';
import {
    type BroadcastTxRequest,
    BroadcastTxRequestFromJSON,
    BroadcastTxRequestToJSON,
} from '../models/BroadcastTxRequest';
import {
    type Healthcheck500Response,
    Healthcheck500ResponseFromJSON,
    Healthcheck500ResponseToJSON,
} from '../models/Healthcheck500Response';

export interface BroadcastTxOperationRequest {
    broadcastTxRequest: BroadcastTxRequest;
}

/**
 * BroadcastApi - interface
 * 
 * @export
 * @interface BroadcastApiInterface
 */
export interface BroadcastApiInterface {
    /**
     * Creates request options for broadcastTx without sending the request
     * @param {BroadcastTxRequest} broadcastTxRequest Signed transaction to broadcast
     * @throws {RequiredError}
     * @memberof BroadcastApiInterface
     */
    broadcastTxRequestOpts(requestParameters: BroadcastTxOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Broadcast a signed transaction
     * @param {BroadcastTxRequest} broadcastTxRequest Signed transaction to broadcast
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BroadcastApiInterface
     */
    broadcastTxRaw(requestParameters: BroadcastTxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastTx200Response>>;

    /**
     * Broadcast a signed transaction
     */
    broadcastTx(requestParameters: BroadcastTxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastTx200Response>;

}

/**
 * 
 */
export class BroadcastApi extends runtime.BaseAPI implements BroadcastApiInterface {

    /**
     * Creates request options for broadcastTx without sending the request
     */
    async broadcastTxRequestOpts(requestParameters: BroadcastTxOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['broadcastTxRequest'] == null) {
            throw new runtime.RequiredError(
                'broadcastTxRequest',
                'Required parameter "broadcastTxRequest" was null or undefined when calling broadcastTx().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/broadcast`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BroadcastTxRequestToJSON(requestParameters['broadcastTxRequest']),
        };
    }

    /**
     * Broadcast a signed transaction
     */
    async broadcastTxRaw(requestParameters: BroadcastTxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastTx200Response>> {
        const requestOptions = await this.broadcastTxRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BroadcastTx200ResponseFromJSON(jsonValue));
    }

    /**
     * Broadcast a signed transaction
     */
    async broadcastTx(requestParameters: BroadcastTxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastTx200Response> {
        const response = await this.broadcastTxRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
