/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Chain,
    ChainFromJSON,
    ChainToJSON,
} from '../models/Chain';
import {
    type FeeEstimate,
    FeeEstimateFromJSON,
    FeeEstimateToJSON,
} from '../models/FeeEstimate';
import {
    type Healthcheck500Response,
    Healthcheck500ResponseFromJSON,
    Healthcheck500ResponseToJSON,
} from '../models/Healthcheck500Response';

export interface GetFeesRequest {
    chain: Chain;
}

/**
 * FeesApi - interface
 * 
 * @export
 * @interface FeesApiInterface
 */
export interface FeesApiInterface {
    /**
     * Creates request options for getFees without sending the request
     * @param {Chain} chain Blockchain identifier
     * @throws {RequiredError}
     * @memberof FeesApiInterface
     */
    getFeesRequestOpts(requestParameters: GetFeesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get fee estimates for a chain
     * @param {Chain} chain Blockchain identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeesApiInterface
     */
    getFeesRaw(requestParameters: GetFeesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeeEstimate>>;

    /**
     * Get fee estimates for a chain
     */
    getFees(requestParameters: GetFeesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeeEstimate>;

}

/**
 * 
 */
export class FeesApi extends runtime.BaseAPI implements FeesApiInterface {

    /**
     * Creates request options for getFees without sending the request
     */
    async getFeesRequestOpts(requestParameters: GetFeesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling getFees().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/fees/{chain}`;
        urlPath = urlPath.replace('{chain}', encodeURIComponent(String(requestParameters['chain'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get fee estimates for a chain
     */
    async getFeesRaw(requestParameters: GetFeesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeeEstimate>> {
        const requestOptions = await this.getFeesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeeEstimateFromJSON(jsonValue));
    }

    /**
     * Get fee estimates for a chain
     */
    async getFees(requestParameters: GetFeesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeeEstimate> {
        const response = await this.getFeesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
