/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetNodes200Response,
    GetNodes200ResponseFromJSON,
    GetNodes200ResponseToJSON,
} from '../models/GetNodes200Response';
import {
    type Healthcheck500Response,
    Healthcheck500ResponseFromJSON,
    Healthcheck500ResponseToJSON,
} from '../models/Healthcheck500Response';

export interface GetNodesRequest {
    ifNoneMatch?: string;
}

/**
 * NodesApi - interface
 * 
 * @export
 * @interface NodesApiInterface
 */
export interface NodesApiInterface {
    /**
     * Creates request options for getNodes without sending the request
     * @param {string} [ifNoneMatch] ETag value from previous response
     * @throws {RequiredError}
     * @memberof NodesApiInterface
     */
    getNodesRequestOpts(requestParameters: GetNodesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get manifest of supported chains
     * @param {string} [ifNoneMatch] ETag value from previous response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NodesApiInterface
     */
    getNodesRaw(requestParameters: GetNodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNodes200Response>>;

    /**
     * Get manifest of supported chains
     */
    getNodes(requestParameters: GetNodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNodes200Response>;

}

/**
 * 
 */
export class NodesApi extends runtime.BaseAPI implements NodesApiInterface {

    /**
     * Creates request options for getNodes without sending the request
     */
    async getNodesRequestOpts(requestParameters: GetNodesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }


        let urlPath = `/api/v1/nodes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get manifest of supported chains
     */
    async getNodesRaw(requestParameters: GetNodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNodes200Response>> {
        const requestOptions = await this.getNodesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNodes200ResponseFromJSON(jsonValue));
    }

    /**
     * Get manifest of supported chains
     */
    async getNodes(requestParameters: GetNodesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNodes200Response> {
        const response = await this.getNodesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
