/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Healthcheck500Response,
    Healthcheck500ResponseFromJSON,
    Healthcheck500ResponseToJSON,
} from '../models/Healthcheck500Response';
import {
    type Ok,
    OkFromJSON,
    OkToJSON,
} from '../models/Ok';

/**
 * SystemApi - interface
 * 
 * @export
 * @interface SystemApiInterface
 */
export interface SystemApiInterface {
    /**
     * Creates request options for healthcheck without sending the request
     * @throws {RequiredError}
     * @memberof SystemApiInterface
     */
    healthcheckRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Check server readiness
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApiInterface
     */
    healthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>>;

    /**
     * Check server readiness
     */
    healthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok>;

}

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI implements SystemApiInterface {

    /**
     * Creates request options for healthcheck without sending the request
     */
    async healthcheckRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/healthcheck`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check server readiness
     */
    async healthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        const requestOptions = await this.healthcheckRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Check server readiness
     */
    async healthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.healthcheckRaw(initOverrides);
        return await response.value();
    }

}
