/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper Multichain Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ActivityType,
    ActivityTypeFromJSON,
    ActivityTypeToJSON,
} from '../models/ActivityType';
import {
    type Asset,
    AssetFromJSON,
    AssetToJSON,
} from '../models/Asset';
import {
    type Chain,
    ChainFromJSON,
    ChainToJSON,
} from '../models/Chain';
import {
    type GetWalletActivities200Response,
    GetWalletActivities200ResponseFromJSON,
    GetWalletActivities200ResponseToJSON,
} from '../models/GetWalletActivities200Response';
import {
    type GetWalletAssets200Response,
    GetWalletAssets200ResponseFromJSON,
    GetWalletAssets200ResponseToJSON,
} from '../models/GetWalletAssets200Response';
import {
    type Healthcheck500Response,
    Healthcheck500ResponseFromJSON,
    Healthcheck500ResponseToJSON,
} from '../models/Healthcheck500Response';
import {
    type RegisterWalletRequest,
    RegisterWalletRequestFromJSON,
    RegisterWalletRequestToJSON,
} from '../models/RegisterWalletRequest';
import {
    type SaveWalletAssetsFiltersRequest,
    SaveWalletAssetsFiltersRequestFromJSON,
    SaveWalletAssetsFiltersRequestToJSON,
} from '../models/SaveWalletAssetsFiltersRequest';
import {
    type SyncStatus,
    SyncStatusFromJSON,
    SyncStatusToJSON,
} from '../models/SyncStatus';
import {
    type SyncWalletV2Request,
    SyncWalletV2RequestFromJSON,
    SyncWalletV2RequestToJSON,
} from '../models/SyncWalletV2Request';
import {
    type Wallet,
    WalletFromJSON,
    WalletToJSON,
} from '../models/Wallet';
import {
    type WalletChallenge,
    WalletChallengeFromJSON,
    WalletChallengeToJSON,
} from '../models/WalletChallenge';

export interface GetWalletRequest {
    walletId: string;
}

export interface GetWalletActivitiesRequest {
    walletId: string;
    limit?: number;
    cursor?: string;
    chain?: Chain;
    activityType?: ActivityType;
}

export interface GetWalletAssetRequest {
    walletId: string;
    assetId: string;
    currencies: Array<string>;
}

export interface GetWalletAssetsRequest {
    walletId: string;
    currencies: Array<string>;
    assetIds?: Array<string>;
    chain?: Chain;
    search?: string;
    availableOnly?: boolean;
    showHidden?: boolean;
    showAll?: boolean;
    limit?: number;
    cursor?: string;
}

export interface GetWalletSyncStatusRequest {
    walletId: string;
}

export interface RegisterWalletOperationRequest {
    registerWalletRequest: RegisterWalletRequest;
}

export interface SaveWalletAssetsFiltersOperationRequest {
    walletId: string;
    saveWalletAssetsFiltersRequest: SaveWalletAssetsFiltersRequest;
}

export interface SyncWalletV2OperationRequest {
    syncWalletV2Request: SyncWalletV2Request;
}

/**
 * WalletsApi - interface
 * 
 * @export
 * @interface WalletsApiInterface
 */
export interface WalletsApiInterface {
    /**
     * Creates request options for getWallet without sending the request
     * @param {string} walletId Stable wallet identifier
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletRequestOpts(requestParameters: GetWalletRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get wallet by id
     * @param {string} walletId Stable wallet identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletRaw(requestParameters: GetWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wallet>>;

    /**
     * Get wallet by id
     */
    getWallet(requestParameters: GetWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet>;

    /**
     * Creates request options for getWalletActivities without sending the request
     * @param {string} walletId Stable wallet identifier
     * @param {number} [limit] Pagination limit
     * @param {string} [cursor] Cursor for pagination
     * @param {Chain} [chain] Filter by chain
     * @param {ActivityType} [activityType] Filter by activity type
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletActivitiesRequestOpts(requestParameters: GetWalletActivitiesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get activity history for a registered wallet
     * @param {string} walletId Stable wallet identifier
     * @param {number} [limit] Pagination limit
     * @param {string} [cursor] Cursor for pagination
     * @param {Chain} [chain] Filter by chain
     * @param {ActivityType} [activityType] Filter by activity type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletActivitiesRaw(requestParameters: GetWalletActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWalletActivities200Response>>;

    /**
     * Get activity history for a registered wallet
     */
    getWalletActivities(requestParameters: GetWalletActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWalletActivities200Response>;

    /**
     * Creates request options for getWalletAsset without sending the request
     * @param {string} walletId Stable wallet identifier
     * @param {string} assetId Asset identifier in chain/network/type[/address] format
     * @param {Array<string>} currencies Base currencies
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletAssetRequestOpts(requestParameters: GetWalletAssetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a single asset of a registered wallet by asset_id
     * @param {string} walletId Stable wallet identifier
     * @param {string} assetId Asset identifier in chain/network/type[/address] format
     * @param {Array<string>} currencies Base currencies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletAssetRaw(requestParameters: GetWalletAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Asset>>;

    /**
     * Get a single asset of a registered wallet by asset_id
     */
    getWalletAsset(requestParameters: GetWalletAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Asset>;

    /**
     * Creates request options for getWalletAssets without sending the request
     * @param {string} walletId Stable wallet identifier
     * @param {Array<string>} currencies Base currencies
     * @param {Array<string>} [assetIds] Filter by asset IDs
     * @param {Chain} [chain] Filter by chain
     * @param {string} [search] Name or symbol of token
     * @param {boolean} [availableOnly] Shows assets with 0 balances or not
     * @param {boolean} [showHidden] Flag to show hidden tokens
     * @param {boolean} [showAll] Shows all possible assets
     * @param {number} [limit] Pagination limit
     * @param {string} [cursor] Cursor for pagination
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletAssetsRequestOpts(requestParameters: GetWalletAssetsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get assets for all accounts of a registered wallet
     * @param {string} walletId Stable wallet identifier
     * @param {Array<string>} currencies Base currencies
     * @param {Array<string>} [assetIds] Filter by asset IDs
     * @param {Chain} [chain] Filter by chain
     * @param {string} [search] Name or symbol of token
     * @param {boolean} [availableOnly] Shows assets with 0 balances or not
     * @param {boolean} [showHidden] Flag to show hidden tokens
     * @param {boolean} [showAll] Shows all possible assets
     * @param {number} [limit] Pagination limit
     * @param {string} [cursor] Cursor for pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletAssetsRaw(requestParameters: GetWalletAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWalletAssets200Response>>;

    /**
     * Get assets for all accounts of a registered wallet
     */
    getWalletAssets(requestParameters: GetWalletAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWalletAssets200Response>;

    /**
     * Creates request options for getWalletChallenge without sending the request
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletChallengeRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Mint a short-lived challenge for signed wallet sync
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletChallengeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletChallenge>>;

    /**
     * Mint a short-lived challenge for signed wallet sync
     */
    getWalletChallenge(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletChallenge>;

    /**
     * Creates request options for getWalletSyncStatus without sending the request
     * @param {string} walletId Stable wallet identifier
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletSyncStatusRequestOpts(requestParameters: GetWalletSyncStatusRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Poll per-chain freshness and backfill progress for a wallet
     * @param {string} walletId Stable wallet identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    getWalletSyncStatusRaw(requestParameters: GetWalletSyncStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncStatus>>;

    /**
     * Poll per-chain freshness and backfill progress for a wallet
     */
    getWalletSyncStatus(requestParameters: GetWalletSyncStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncStatus>;

    /**
     * Creates request options for registerWallet without sending the request
     * @param {RegisterWalletRequest} registerWalletRequest Register a wallet with its accounts
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    registerWalletRequestOpts(requestParameters: RegisterWalletOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Register a wallet with its accounts
     * @param {RegisterWalletRequest} registerWalletRequest Register a wallet with its accounts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    registerWalletRaw(requestParameters: RegisterWalletOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wallet>>;

    /**
     * Register a wallet with its accounts
     */
    registerWallet(requestParameters: RegisterWalletOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet>;

    /**
     * Creates request options for saveWalletAssetsFilters without sending the request
     * @param {string} walletId Stable wallet identifier
     * @param {SaveWalletAssetsFiltersRequest} saveWalletAssetsFiltersRequest Set asset hidden/shown filter
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    saveWalletAssetsFiltersRequestOpts(requestParameters: SaveWalletAssetsFiltersOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Set wallet\'s assets hidden/shown settings
     * @param {string} walletId Stable wallet identifier
     * @param {SaveWalletAssetsFiltersRequest} saveWalletAssetsFiltersRequest Set asset hidden/shown filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    saveWalletAssetsFiltersRaw(requestParameters: SaveWalletAssetsFiltersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Set wallet\'s assets hidden/shown settings
     */
    saveWalletAssetsFilters(requestParameters: SaveWalletAssetsFiltersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for syncWalletV2 without sending the request
     * @param {SyncWalletV2Request} syncWalletV2Request 
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    syncWalletV2RequestOpts(requestParameters: SyncWalletV2OperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Sync a signed v2 wallet registration
     * @param {SyncWalletV2Request} syncWalletV2Request 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApiInterface
     */
    syncWalletV2Raw(requestParameters: SyncWalletV2OperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncStatus>>;

    /**
     * Sync a signed v2 wallet registration
     */
    syncWalletV2(requestParameters: SyncWalletV2OperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncStatus>;

}

/**
 * 
 */
export class WalletsApi extends runtime.BaseAPI implements WalletsApiInterface {

    /**
     * Creates request options for getWallet without sending the request
     */
    async getWalletRequestOpts(requestParameters: GetWalletRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletId'] == null) {
            throw new runtime.RequiredError(
                'walletId',
                'Required parameter "walletId" was null or undefined when calling getWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/wallets/{wallet_id}`;
        urlPath = urlPath.replace('{wallet_id}', encodeURIComponent(String(requestParameters['walletId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get wallet by id
     */
    async getWalletRaw(requestParameters: GetWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wallet>> {
        const requestOptions = await this.getWalletRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletFromJSON(jsonValue));
    }

    /**
     * Get wallet by id
     */
    async getWallet(requestParameters: GetWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet> {
        const response = await this.getWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWalletActivities without sending the request
     */
    async getWalletActivitiesRequestOpts(requestParameters: GetWalletActivitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletId'] == null) {
            throw new runtime.RequiredError(
                'walletId',
                'Required parameter "walletId" was null or undefined when calling getWalletActivities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['chain'] != null) {
            queryParameters['chain'] = requestParameters['chain'];
        }

        if (requestParameters['activityType'] != null) {
            queryParameters['activity_type'] = requestParameters['activityType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/wallets/{wallet_id}/activities`;
        urlPath = urlPath.replace('{wallet_id}', encodeURIComponent(String(requestParameters['walletId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get activity history for a registered wallet
     */
    async getWalletActivitiesRaw(requestParameters: GetWalletActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWalletActivities200Response>> {
        const requestOptions = await this.getWalletActivitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWalletActivities200ResponseFromJSON(jsonValue));
    }

    /**
     * Get activity history for a registered wallet
     */
    async getWalletActivities(requestParameters: GetWalletActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWalletActivities200Response> {
        const response = await this.getWalletActivitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWalletAsset without sending the request
     */
    async getWalletAssetRequestOpts(requestParameters: GetWalletAssetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletId'] == null) {
            throw new runtime.RequiredError(
                'walletId',
                'Required parameter "walletId" was null or undefined when calling getWalletAsset().'
            );
        }

        if (requestParameters['assetId'] == null) {
            throw new runtime.RequiredError(
                'assetId',
                'Required parameter "assetId" was null or undefined when calling getWalletAsset().'
            );
        }

        if (requestParameters['currencies'] == null) {
            throw new runtime.RequiredError(
                'currencies',
                'Required parameter "currencies" was null or undefined when calling getWalletAsset().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['assetId'] != null) {
            queryParameters['asset_id'] = requestParameters['assetId'];
        }

        if (requestParameters['currencies'] != null) {
            queryParameters['currencies'] = requestParameters['currencies']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/wallets/{wallet_id}/asset`;
        urlPath = urlPath.replace('{wallet_id}', encodeURIComponent(String(requestParameters['walletId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single asset of a registered wallet by asset_id
     */
    async getWalletAssetRaw(requestParameters: GetWalletAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Asset>> {
        const requestOptions = await this.getWalletAssetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetFromJSON(jsonValue));
    }

    /**
     * Get a single asset of a registered wallet by asset_id
     */
    async getWalletAsset(requestParameters: GetWalletAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Asset> {
        const response = await this.getWalletAssetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWalletAssets without sending the request
     */
    async getWalletAssetsRequestOpts(requestParameters: GetWalletAssetsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletId'] == null) {
            throw new runtime.RequiredError(
                'walletId',
                'Required parameter "walletId" was null or undefined when calling getWalletAssets().'
            );
        }

        if (requestParameters['currencies'] == null) {
            throw new runtime.RequiredError(
                'currencies',
                'Required parameter "currencies" was null or undefined when calling getWalletAssets().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['assetIds'] != null) {
            queryParameters['asset_ids'] = requestParameters['assetIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['chain'] != null) {
            queryParameters['chain'] = requestParameters['chain'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['availableOnly'] != null) {
            queryParameters['available_only'] = requestParameters['availableOnly'];
        }

        if (requestParameters['showHidden'] != null) {
            queryParameters['show_hidden'] = requestParameters['showHidden'];
        }

        if (requestParameters['showAll'] != null) {
            queryParameters['show_all'] = requestParameters['showAll'];
        }

        if (requestParameters['currencies'] != null) {
            queryParameters['currencies'] = requestParameters['currencies']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/wallets/{wallet_id}/assets`;
        urlPath = urlPath.replace('{wallet_id}', encodeURIComponent(String(requestParameters['walletId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get assets for all accounts of a registered wallet
     */
    async getWalletAssetsRaw(requestParameters: GetWalletAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWalletAssets200Response>> {
        const requestOptions = await this.getWalletAssetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWalletAssets200ResponseFromJSON(jsonValue));
    }

    /**
     * Get assets for all accounts of a registered wallet
     */
    async getWalletAssets(requestParameters: GetWalletAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWalletAssets200Response> {
        const response = await this.getWalletAssetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWalletChallenge without sending the request
     */
    async getWalletChallengeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/wallets/challenge`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mint a short-lived challenge for signed wallet sync
     */
    async getWalletChallengeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletChallenge>> {
        const requestOptions = await this.getWalletChallengeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletChallengeFromJSON(jsonValue));
    }

    /**
     * Mint a short-lived challenge for signed wallet sync
     */
    async getWalletChallenge(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletChallenge> {
        const response = await this.getWalletChallengeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWalletSyncStatus without sending the request
     */
    async getWalletSyncStatusRequestOpts(requestParameters: GetWalletSyncStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletId'] == null) {
            throw new runtime.RequiredError(
                'walletId',
                'Required parameter "walletId" was null or undefined when calling getWalletSyncStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/wallets/{wallet_id}/sync_status`;
        urlPath = urlPath.replace('{wallet_id}', encodeURIComponent(String(requestParameters['walletId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Poll per-chain freshness and backfill progress for a wallet
     */
    async getWalletSyncStatusRaw(requestParameters: GetWalletSyncStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncStatus>> {
        const requestOptions = await this.getWalletSyncStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SyncStatusFromJSON(jsonValue));
    }

    /**
     * Poll per-chain freshness and backfill progress for a wallet
     */
    async getWalletSyncStatus(requestParameters: GetWalletSyncStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncStatus> {
        const response = await this.getWalletSyncStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerWallet without sending the request
     */
    async registerWalletRequestOpts(requestParameters: RegisterWalletOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerWalletRequest'] == null) {
            throw new runtime.RequiredError(
                'registerWalletRequest',
                'Required parameter "registerWalletRequest" was null or undefined when calling registerWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/wallets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterWalletRequestToJSON(requestParameters['registerWalletRequest']),
        };
    }

    /**
     * Register a wallet with its accounts
     */
    async registerWalletRaw(requestParameters: RegisterWalletOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wallet>> {
        const requestOptions = await this.registerWalletRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletFromJSON(jsonValue));
    }

    /**
     * Register a wallet with its accounts
     */
    async registerWallet(requestParameters: RegisterWalletOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet> {
        const response = await this.registerWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for saveWalletAssetsFilters without sending the request
     */
    async saveWalletAssetsFiltersRequestOpts(requestParameters: SaveWalletAssetsFiltersOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletId'] == null) {
            throw new runtime.RequiredError(
                'walletId',
                'Required parameter "walletId" was null or undefined when calling saveWalletAssetsFilters().'
            );
        }

        if (requestParameters['saveWalletAssetsFiltersRequest'] == null) {
            throw new runtime.RequiredError(
                'saveWalletAssetsFiltersRequest',
                'Required parameter "saveWalletAssetsFiltersRequest" was null or undefined when calling saveWalletAssetsFilters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/wallets/{wallet_id}/assets`;
        urlPath = urlPath.replace('{wallet_id}', encodeURIComponent(String(requestParameters['walletId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveWalletAssetsFiltersRequestToJSON(requestParameters['saveWalletAssetsFiltersRequest']),
        };
    }

    /**
     * Set wallet\'s assets hidden/shown settings
     */
    async saveWalletAssetsFiltersRaw(requestParameters: SaveWalletAssetsFiltersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.saveWalletAssetsFiltersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set wallet\'s assets hidden/shown settings
     */
    async saveWalletAssetsFilters(requestParameters: SaveWalletAssetsFiltersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.saveWalletAssetsFiltersRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for syncWalletV2 without sending the request
     */
    async syncWalletV2RequestOpts(requestParameters: SyncWalletV2OperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['syncWalletV2Request'] == null) {
            throw new runtime.RequiredError(
                'syncWalletV2Request',
                'Required parameter "syncWalletV2Request" was null or undefined when calling syncWalletV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v2/wallets/sync`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SyncWalletV2RequestToJSON(requestParameters['syncWalletV2Request']),
        };
    }

    /**
     * Sync a signed v2 wallet registration
     */
    async syncWalletV2Raw(requestParameters: SyncWalletV2OperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncStatus>> {
        const requestOptions = await this.syncWalletV2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SyncStatusFromJSON(jsonValue));
    }

    /**
     * Sync a signed v2 wallet registration
     */
    async syncWalletV2(requestParameters: SyncWalletV2OperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncStatus> {
        const response = await this.syncWalletV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
